import json
from pathlib import Path
R=Path(__file__).resolve().parents[3]
refs={
'frames':'https://raw.githubusercontent.com/ros-infrastructure/rep/master/rep-0103.rst',
'rigid':'https://modernrobotics.northwestern.edu/nu-gm-book-resource/3-3-1-homogeneous-transformation-matrices/',
'camera':'https://docs.opencv.org/4.13.0/d9/d0c/group__calib3d.html',
'board':'https://docs.opencv.org/4.10.0/dc/dbb/tutorial_py_calibration.html',
'lidar':'https://docs.ouster.com/sensor-docs/coordinate-system',
'extrinsic':'https://www.mathworks.com/help/lidar/ug/lidar-camera-calibration.html'}
C=[]
def add(title,layout='text',body=None,take='',media=None,notes='',sources=None,**kw):
 C.append(dict(title=title,layout=layout,body=body or [],take=take,media=media or [],notes=notes,refs=[refs[s] for s in sources or []],**kw))
add('Sensor fusion for autonomous driving','cover',body=['LECTURE 4','Coordinate frames, sensor models, and calibration','Introduction to Autonomous Driving · Fall 2026'],notes='Plan for roughly 80–90 minutes including live demonstrations. For a 75-minute class, shorten optional board fitting and fusion-level discussion. Open the offline SensorFusion/index.html before class. Five experiments share a single browser page. All demo scenes are synthetic.')
add('Why camera and LiDAR belong together','table',take='Fusion begins by making measurements geometrically comparable.',table=[['Sensor','Useful evidence','Common limitation'],['Camera','Appearance, markings, object class','Monocular depth is ambiguous'],['LiDAR','Metric range and 3D structure','Sparse angular samples'],['Together','Appearance attached to geometry','Requires alignment and association']],notes='Connect to Lectures 2–3: a detector can label an object in image pixels. A planner needs a spatial estimate. Discuss a car visible in an image and several nearby LiDAR clusters. Neither stream alone tells us which measurements correspond. This qualitative comparison motivates the lesson, rather than claiming that fusion guarantees improvement.')
add('A coordinate needs a frame','visual',body=['A frame defines an origin and oriented axes.','The same hand has different coordinates in the base and link frames.'],media=['arm.png'],take='Always attach a frame name and units to a position.',sources=['frames'],notes='Point at the base axes, then the axes on the final link. Ask whether the hand moved when we changed the coordinate frame used to describe it. It did not. In the demo each link frame is at the distal end. A point at that origin is (0,0) in its own frame. Axes are x red and y green. Planar example, metres.')
add('Links and actuators','visual',body=['A rigid link has fixed geometry.','A rotary joint changes angle. A sliding joint changes extension.','Each link carries its own frame.'],media=['arm-added-3d.png'],take='Joint values determine the relative transforms along the chain.',notes='Live preview only, save the longer interaction for slide 7. The fixed-link button adds a rigid segment with a fixed mount angle. A rotary segment has a variable angle followed by its fixed link length. A prismatic segment extends along its mounted local x axis. These are kinematic models of actuated joints, not motor or dynamics simulations.',sources=['rigid'])
add('Rotation and translation in one matrix','equation',body=['T_AB converts coordinates from frame B into frame A.','R_AB gives orientation. t_AB is the B-origin expressed in A.'],equations=['p_A = R_AB p_B + t_AB','[ p_A ]   [ R_AB   t_AB ] [ p_B ]','[   1   ] = [   0          1    ] [   1   ]'],take='In 3D, T is 4 × 4. Our planar demo uses a 3 × 3 version.',notes='Use column vectors throughout. Say the destination frame first and the source frame second. t is not the position of A expressed in B. Explain the final homogeneous coordinate 1: it lets translation enter matrix multiplication. Rotation and translation units differ. All demo angles display degrees, then convert to radians for trigonometry.',sources=['rigid'])
add('Forward kinematics: a worked example','visual',body=['L₁ = L₂ = 1 m','q₁ = 90°, q₂ = −90°','x = cos 90° + cos 0° = 1','y = sin 90° + sin 0° = 1'],media=['arm-worked.png'],take='T₀₂ = T₀₁ T₁₂ gives the hand at (1, 1) m.',notes='For the endpoint-frame convention, T_previous,current = Rot(q) Trans_x(L). The first endpoint is (0,1). The second joint is −90 degrees relative to the first link, so its absolute angle is zero. The second endpoint is (1,1). q2 is not an absolute world angle. The hand orientation is q1+q2=0 degrees. Matrix multiplication order matters.',sources=['rigid'])
add('Demo 1: build and inspect a robot arm','demo',body=['Add a rotary link, then a sliding joint.','Change a parent angle. Predict which frames move.','Inspect a local matrix and its cumulative product.','Challenge: reach (1, 1) m with two 1 m links.'],media=['arm.png'],take='Open SensorFusion/index.html and choose “1 · Robot arm”.',demo='arm',notes='Allow 6–8 minutes. Reset first. Ask students to predict before moving sliders. Select Frame 2 to see parent-to-link and base-to-link matrices together. Add a slider and show that it follows the rotated local x direction. Challenge solution: 90 and −90 degrees, or 0 and 90 degrees. Compare the different hand orientations. Use reset after changing links. Keep index.html, lab.js, scene3d.js, and the vendor folder together. Extract the whole ZIP before opening the demos.',sources=['rigid'])
add('Vehicle and camera axis conventions','table',table=[['Frame','Axes','Role'],['Vehicle body','x forward, y left, z up','A common 3D reference'],['Camera optical','x right, y down, z forward','Pinhole projection'],['LiDAR','Check driver conventions','Range points in sensor frame'],['Image pixels','u right, v down','2D image coordinates']],take='Axis conversion is part of the extrinsic transform.',notes='ROS REP 103 defines body and optical conventions. A vendor LiDAR coordinate system can differ, so inspect its documentation and driver. Do not feed body-frame x into the optical depth denominator. For an aligned camera, Xc=−Ybody, Yc=−Zbody, Zc=Xbody before accounting for translation. A tf tree tracks named frames, while calibration supplies the rigid sensor transforms.',sources=['frames','lidar'])
add('The pinhole camera model','visual',body=['A scene point is (X, Y, Z) in the optical frame.','Divide by depth: x = X/Z, y = Y/Z.','Points behind the camera need rejection.'],media=['camera.png'],take='Projection turns a 3D ray into an image location.',notes='The synthetic scene shows road lines converging toward the horizon. Compare the same-size object at different distances: normalized image size decreases with Z. Many different points along one optical ray map to the same ideal pixel. This is why a single pixel does not directly reveal metric depth. The scene uses wireframes to make projection easy to see.',sources=['camera'])
add('Camera intrinsics K','equation',equations=['K = [ fₓ    0    cₓ ]','       [  0    fᵧ    cᵧ ]','       [  0     0      1 ]','u = fₓ X/Z + cₓ     v = fᵧ Y/Z + cᵧ'],body=['fₓ and fᵧ are focal lengths in pixels.','(cₓ, cᵧ) is the principal point. The demo assumes zero skew.'],take='Intrinsics map normalized rays to pixel coordinates.',notes='Distinguish focal length in millimetres from focal length expressed in pixel units. Different horizontal and vertical pixel scaling can make fx and fy differ. The principal point is often near the image centre but should not be assumed to equal it. K alone omits lens distortion.',sources=['camera'])
add('Focal length changes the field of view','pair',media=['camera.png','camera-zoom.png'],labels=['fₓ = fᵧ = 600 px','fₓ = fᵧ = 1200 px'],body=['Same 800 × 500 image and fixed camera pose.','For a centred pinhole: FOVₓ = 2 atan(W / 2fₓ).'],take='Doubling focal length magnifies the scene and narrows the view.',notes='Worked horizontal FOV: W=800 and fx=600 gives about 67.4 degrees. fx=1200 gives about 36.9 degrees. Derive it from the right triangle formed by half the image width and focal length. This simple symmetric formula assumes centred principal point and no distortion. The demo uses the sum of left and right angles when cx is off-centre.',sources=['camera'])
add('Demo 2: change the camera intrinsics','demo',media=['camera-shift.png'],body=['Double fₓ and fᵧ, then reset.','Change cₓ only. Compare position and size.','Change fₓ only. Observe horizontal stretching.','Predict where (1, 0, 10) m lands.'],take='Open “2 · Camera”. Baseline point projection: (460, 250) px.',demo='camera',notes='Allow 5 minutes. Baseline K is fx=fy=600, cx=400, cy=250. u=600*(1/10)+400=460 and v=250. Doubling both focal lengths changes u to 520 without moving the principal point. Increasing cx by 100 shifts all ideal projections 100 px to the right. Changing only fx changes horizontal scale. Editing real camera metadata alone does not change its captured pixels.',sources=['camera'])
add('Distortion, resizing, and cropping','visual',media=['camera-distortion.png'],body=['Radial distortion bends straight lines.','Resizing by s scales fₓ, fᵧ, cₓ, and cᵧ.','Cropping at (x₀, y₀) subtracts that offset from the principal point.'],take='The calibration must match the actual image passed to fusion.',notes='The demo uses only k1 on normalized coordinates: xd=x(1+k1*r²), yd=y(1+k1*r²). Real models may include more radial terms and tangential distortion. Cropping does not change focal lengths in pixels if pixel size is unchanged. Nonuniform resizing uses separate sx and sy. State the pixel-coordinate convention when doing exact resampling. Rectified images require the new projection matrix rather than blindly reusing raw-image K.',sources=['camera'])
add('LiDAR measures range along a beam','equation',equations=['r = c Δt / 2','x = r cos φ cos θ','y = r cos φ sin θ     z = r sin φ'],body=['Time-of-flight LiDAR measures a round trip.','θ is azimuth. φ is elevation. r is slant range.'],take='A point cloud depends on both ranges and beam directions.',notes='c is the speed of light. The first equation illustrates pulsed time of flight, not every possible LiDAR architecture. The spherical equations use an ideal beam origin. Real sensor conversion can include beam offsets and per-beam calibration. Ouster documentation supplies a concrete example where naive spherical conversion omits sensor-specific terms.',sources=['lidar'])
add('360° scanning and vertical field of view','visual',media=['lidar-3d.png'],body=['Horizontal coverage: 360°','Upper / lower: +15° / −25°','Vertical FOV: 40°','Sensor height: 1.8 m'],take='The lower beam limit controls near-ground coverage.',notes='Elevation is measured from the sensor horizontal plane. These are illustrative simulator settings, not specifications for a particular model. On unobstructed flat ground the lowest beam hits at h/tan(abs(lower)) = 1.8/tan(25 degrees), approximately 3.86 m. Mount pitch and terrain change this distance. This spinning LiDAR has fixed full 360-degree horizontal coverage. Orbit the 3D view to inspect returns behind the vehicle as well as in front. The scan fan is slowed for teaching. The ego car is a mounting reference and is excluded from self-returns.',sources=['lidar'])
add('More beams and wider FOV differ','pair',media=['lidar-16-3d.png','lidar-dense-3d.png'],labels=['16 channels over 40°','64 channels over 40°'],body=['At fixed vertical FOV, more channels reduce beam spacing.','At fixed channels, a wider vertical FOV increases spacing.'],take='Coverage and angular resolution describe different properties.',notes='For this uniformly spaced toy sensor with endpoints included, elevation spacing = (upper−lower)/(N−1). Values are 2.67 degrees for 16 and 0.635 degrees for 64. Nearby rays separate further in metres at longer range: approximately r times angular spacing in radians. Real hardware may use nonuniform elevation patterns. More channels alone does not guarantee returns from every object.',sources=['lidar'])
add('Demo 3: coverage and missing returns','demo',media=['lidar-blind-3d.png'],body=['Raise the lower limit to −5°.','Compare sparse and dense scan presets.','Orbit behind the car and inspect rear returns.','Compare scene and point-cloud modes.'],take='Open “3 · LiDAR”. Missing points can come from sampling geometry.',demo='lidar',notes='Allow 5–6 minutes. At 1.8 m height, the −5-degree beam meets flat ground at roughly 20.57 m, versus 3.86 m for −25 degrees. A wider azimuth step reduces rays per scan and can skip small targets. Maximum range clips slant range, not horizontal distance. Controls describe a hypothetical configurable sensor, not promises of software-adjustable hardware beam count. Demonstration uses ideal single returns on matching cuboid scene surfaces. Show the pause and 15-degree step controls, then change point color from range to height. Click an object to see its return count. Horizontal coverage remains 360 degrees in every preset.',sources=['lidar'])
add('Intrinsic and extrinsic calibration','table',table=[['Quantity','What it describes','Examples'],['Camera intrinsic','Pixel formation inside a camera','K and lens distortion'],['LiDAR intrinsic','Beam and range model','Beam angles and offsets'],['Sensor extrinsic','Rigid pose between sensors','Rotation R and translation t'],['Time alignment','When a measurement occurred','Clock offset and scan timing']],take='Changing a sensor mount changes extrinsics even if K stays the same.',notes='Ask students to classify a camera lens zoom, a shifted camera bracket, an image crop, and a clock offset. Zoom and crop affect the relevant camera model; bracket shift affects extrinsics; time offset requires temporal treatment. Intrinsic parameters can vary with the operating configuration. Do not use an extrinsic adjustment to hide bad timestamps.',sources=['camera','lidar','extrinsic'])
add('Why a checkerboard works','visual',media=['board-tilt.png'],body=['Known square size defines 3D board points.','High-contrast intersections give repeatable image corners.','9 × 6 inner corners require 10 × 7 squares.'],take='Each detected corner pairs a known board point with a measured pixel.',notes='Define board coordinates Pij=(i*s,j*s,0) with known square size s. The physical target is planar even though each camera view has its own 3D pose. Explain inner corners rather than square count. The illustrative target has 0.20 m squares; choose an appropriate physical size and measure it for a real setup. Wrong square size mainly rescales recovered translations in the ideal monocular setup.',sources=['board'])
add('A camera calibration workflow','steps',body=['Capture a rigid, flat target at varied tilts, distances, and image locations.','Detect inner corners and refine their pixel positions.','Estimate K, distortion, and a board pose for each view.','Check residuals and straight lines on held-out views.'],take='Repeated front-facing images provide weak geometric diversity.',notes='Use sharp images and hold the camera focus/zoom and output resolution fixed. Include coverage near image edges where distortion matters. Minimize observed-minus-projected corner residuals across all views. Report per-view errors as well as overall RMS. Low training error alone does not prove a useful calibration. A warped target can bias the fit. Distinguish board-to-camera pose for one view from the fixed camera-to-LiDAR transform.',sources=['board','camera'])
add('Demo 4: corner reprojection error','pair',media=['board-before.png','board-fit.png'],labels=['Initial estimate: residuals remain','Fitted K: corners align'],body=['Adjust focal length and principal point, then choose “Fit K”.','The demo knows board pose and assumes zero distortion.'],take='Open “4 · Checkerboard”. Real calibration also estimates unknown poses.',demo='calibration',notes='Allow 4 minutes. Orange dots are observations; blue rings are projections from the estimate; connecting segments are residuals. The noise-free known-pose fit recovers fx=fy=800, cx=410, cy=245. Tilting the board after fitting keeps agreement. This is a least-squares illustration, not a replacement for OpenCV calibrateCamera. Discuss what extra unknowns and measurement noise arise in an actual experiment.',sources=['board'])
add('A shared target links camera and LiDAR','text',body=['The camera observes printed corners and estimates the board pose.','LiDAR returns describe the board surface, edges, or other detectable geometry.','Multiple target poses constrain one fixed camera–LiDAR rotation and translation.','Validation projects new LiDAR measurements into new images.'],take='LiDAR does not automatically observe the printed corner grid.',notes='A checkerboard enables camera pose recovery. Many LiDAR-camera workflows extract a rectangular board plane and boundaries from the point cloud; the exact target and estimator determine required geometry. A single plane with only normal and distance leaves in-plane translation and rotation ambiguity. Use multiple diverse poses and sufficient returns. Do not match an arbitrary LiDAR point to each printed corner. MathWorks documents a practical checkerboard-target workflow.',sources=['extrinsic'])
add('The LiDAR-to-image projection chain','equation',equations=['p_C = R_CL p_L + t_CL','x = X_C / Z_C     y = Y_C / Z_C','(x, y) → distortion model → (xᵈ, yᵈ)','u = fₓ xᵈ + cₓ     v = fᵧ yᵈ + cᵧ'],body=['Transform to the optical frame before dividing by depth.','Keep Z_C > 0 and image coordinates inside the image.'],take='Raw and rectified images require the matching projection model.',notes='T_CL maps from LiDAR L into camera C. If a calibration file supplies T_LC, invert it: R_CL=R_LC transpose, t_CL=−R_LC transpose times t_LC. Reject invalid range values before projection. For rectified output, use its rectified model and appropriate transform. Image bounds alone do not establish visibility or correspondence.',sources=['camera','extrinsic'])
add('A worked LiDAR-to-pixel example','equation',equations=['p_L = (10, −1, 0.5) m','p_C = (−Y_L, 1.5 − Z_L, X_L) = (1, 1, 10) m','u = 600 × 1/10 + 400 = 460 px','v = 600 × 1/10 + 250 = 310 px'],body=['LiDAR: x forward, y left, z up at ground level.','Camera: 1.5 m above the LiDAR origin, with aligned forward axes.'],take='The 10 m forward distance becomes optical depth Z_C.',notes='Teaching mounting geometry only. Camera optical axes are right, down, forward. R_CL rows are [0,-1,0], [0,0,-1], [1,0,0] and t_CL=[0,1.5,0]. This is a proper rotation with determinant +1. Assume zero distortion and K=[600,0,400;0,600,250;0,0,1]. The point lies inside an 800 by 500 image.',sources=['frames','camera'])
add('Demo 5: diagnose alignment errors','demo',media=['fusion-fault.png'],body=['Introduce a fault, then change one parameter at a time.','Compare yaw and translation across target depths.','Restore geometry before changing the time offset.'],take='Open “5 · Fusion”. Orange is the reference, blue is your projection.',demo='fusion',notes='Allow 5–6 minutes. The demo draws synthetic point planes at 10,20,35 m, independent of background objects, to isolate geometric effects. Angular error gives roughly depth-independent pixel shift near the optical axis. Translation gives a stronger shift for nearby points. Reset gives exact reference agreement. This demonstration does not perform detection, data association, or real calibration.',sources=['camera'])
add('Time misalignment looks like geometry error','visual',media=['fusion-time.png'],body=['Object speed: 10 m/s','Time offset: 100 ms','Position mismatch: 1 m','At 10 m and fₓ = 600 px: about 60 px lateral error'],take='Extrinsic calibration cannot fix a measurement taken at the wrong time.',notes='Use delta position = speed times delta time. For pure lateral motion and fixed depth, pixel displacement = fx times lateral displacement divided by depth. The demo treats target motion as constant, with exact timestamps and no ego-motion. Real systems need clock alignment, timestamp-aware matching, and motion compensation. A rotating LiDAR sweep contains measurements from different instants, so matching a single frame stamp alone does not deskew the sweep.')
add('Visibility and data association','text',body=['A point inside an image may lie behind another surface.','Different sensor positions create different occlusion boundaries.','A detection box can contain returns from the road and background.','Association must consider depth, visibility, and object geometry.'],take='A projected point inside a box is only a candidate match.',notes='Thought experiment: a pedestrian stands in front of a wall. Both can project into the person’s 2D bounding box. A median over every enclosed range can select the background if it dominates. Separate clusters and check plausible foreground geometry. A z-buffer can help with depth ordering when enough geometry exists, but sparse LiDAR does not provide complete camera visibility. This is the transition from coordinate alignment to a meaningful fusion algorithm.')
add('Fusion needs an uncertainty model','equation',equations=['x̂ = (x₁/σ₁² + x₂/σ₂²) / (1/σ₁² + 1/σ₂²)','x₁ = 10.0 m, σ₁ = 0.2 m','x₂ = 11.0 m, σ₂ = 1.0 m','x̂ ≈ 10.04 m     σ ≈ 0.196 m'],body=['Toy example: two unbiased, independent estimates of the same scalar.','Correlated errors and wrong associations violate these assumptions.'],take='More measurements help only when their meaning and reliability are sound.',notes='Derive inverse-variance weighting by minimizing (x−x1)^2/sigma1^2+(x−x2)^2/sigma2^2. Weights are 25 and 1. Fused variance is 1/26. These are invented teaching values, not measured sensor accuracy. A monocular detector box is not directly a second metric range measurement. Shared calibration errors can correlate estimates and make naive uncertainty reduction overconfident. This introduces filtering without attempting a full Kalman filter lesson.')
add('Where fusion can happen','table',table=[['Level','What combines','Example'],['Measurements','Projected or aligned samples','Attach image colour to 3D points'],['Features','Learned representations','Combine image and point-cloud features'],['Objects / tracks','Detections or state estimates','Associate and update an object track']],take='Every level still needs geometry, timing, and a defensible association.',notes='These categories vary across literature, so present them as a useful organizing scheme. Point colourization is a simple geometrically aligned measurement example, not full object detection. Feature fusion connects to Lecture 3 neural representations. Track fusion may handle asynchronous observations with a motion model. Do not imply a particular fusion architecture always wins.')
add('Exit ticket and further reading','resources',body=['Compose two link transforms and state the hand frame.','Explain how fₓ changes FOV at fixed image width.','Explain why a LiDAR point can miss its matching image object.'],take='Five local demos: SensorFusion/index.html',notes='Ask students for one geometry error and one timing or visibility error. Expected answers: compose in the correct order and state frame/units; increasing fx narrows ideal FOV; calibration, timestamps, occlusion, sampling, and association can each matter. Revisit the lowest-beam ground-distance prediction if time permits. Further reading links are clickable in the slide.',sources=['rigid','camera','board','lidar','extrinsic'],links=[['Modern Robotics: transforms',refs['rigid']],['OpenCV: camera calibration',refs['board']],['Ouster: beam coordinates',refs['lidar']],['LiDAR–camera calibration',refs['extrinsic']]])
# Keep the live activity aligned with the channel/range experiment.
C[16].update(title='Demo 3: channels and perception at range',
 body=['Compare 8, 32, and 128 channels at fixed FOV.',
       'Inspect identical targets at 10, 30, and 60 m.',
       'Increase the horizontal angular step.',
       'Raise the lower limit to −5° and compare.'],
 media=['lidar-range.png'],
 take='Open “3 · LiDAR”. Fewer returns leave less evidence for perception.')
C[16]['notes'] += ' Use the density panel below the 3D scene. Reset to the 40-degree vertical FOV and 1-degree horizontal step, with maximum range 80 m. At 8 channels, the isolated targets at 10/30/60 m return 6/1/0 points. At 32 channels they return 24/3/1, and at 128 channels 99/11/6. The image shows 128 channels. Targets are each 0.6 m wide and 1.8 m tall, independently sampled without scene occlusion. Counts are geometric evidence, not detection probabilities. Changing the channel count resamples uniformly spaced beam elevations, so individual target counts need not change monotonically. Distinguish channels hitting a target from total points returned.'

assert len(C)==30
for i,c in enumerate(C,1):c['slide']=i
(R/'tools/slides/lecture4/content.json').write_text(json.dumps(C,ensure_ascii=False,indent=2))
