const {chromium}=require('/home/william/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/google-chrome'});const page=await browser.newPage({viewport:{width:1500,height:1100},deviceScaleFactor:1});let errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+path.resolve('2026/Labs/SensorFusion/index.html')+'#lidar');assert(await page.evaluate(()=>FusionScene.getStatus().ready));assert(!await page.locator('body').evaluate(e=>e.classList.contains('fallback-2d')));
const shot=async(name)=>{await page.locator('#world3d').screenshot({path:'.build/slides/lecture4/assets/'+name+'.png'})};
await page.click('#scan-play');assert.equal(await page.evaluate(()=>FusionScene.getStatus().playing),false);let phase=await page.evaluate(()=>FusionScene.getStatus().phase);await page.click('#scan-step');let p2=await page.evaluate(()=>FusionScene.getStatus().phase);assert(Math.abs((p2-phase+360)%360-15)<.001);let initial=await page.evaluate(()=>({s:FusionScene.getStatus(),points:Lab.scanLidar(Lab.state.lidar).pts}));assert.equal(initial.s.rays,32*360);for(let axis of [0,1])for(let sign of [-1,1])assert(initial.points.some(p=>p.p[axis]*sign>5));assert.equal(await page.locator('#hfov').count(),0);
await shot('lidar-3d');await page.selectOption('#display-mode','points');assert.equal(await page.evaluate(()=>FusionScene.getStatus().viewMode),'points');await page.selectOption('#point-color','height');assert.equal(await page.evaluate(()=>FusionScene.getStatus().colorMode),'height');await page.check('#envelope');await page.uncheck('#frames');await shot('lidar-points');await page.selectOption('#display-mode','overlay');await page.selectOption('#point-color','range');await page.uncheck('#envelope');await page.check('#frames');
await page.locator('#channels').fill('16');await page.locator('#channels').dispatchEvent('input');await shot('lidar-16-3d');await page.click('[data-preset=dense]');assert.equal(await page.evaluate(()=>Lab.state.lidar.hfov),360);assert.equal(await page.evaluate(()=>Lab.state.lidar.channels),64);await page.locator('#step').fill('1');await page.locator('#step').dispatchEvent('input');await shot('lidar-dense-3d');await page.click('[data-preset=blind]');assert.equal(await page.evaluate(()=>Lab.state.lidar.lower),-5);await shot('lidar-blind-3d');await page.click('[data-preset=street]');await page.screenshot({path:'.build/slides/lecture4/revised-lidar-desktop.png',fullPage:true});
await page.click('[data-tab=arm]');assert.equal(await page.evaluate(()=>FusionScene.getStatus().tab),'arm');await shot('arm-3d');await page.click('#add-p');await page.click('#add-f');await shot('arm-added-3d');await page.click('[data-tab=camera]');await shot('camera-3d');await page.click('#zoom');await shot('camera-zoom-3d');await page.click('[data-tab=calibration]');await shot('board-3d');await page.click('[data-tab=fusion]');await shot('fusion-3d');
for(let width of [800,390]){await page.setViewportSize({width,height:1000});await page.click('[data-tab=lidar]');let positions=await page.evaluate(()=>({canvas:document.querySelector('#world3d').getBoundingClientRect().top,controls:document.querySelector('.controls').getBoundingClientRect().top,overflow:document.documentElement.scrollWidth>window.innerWidth}));assert(positions.canvas<positions.controls);assert(!positions.overflow);await page.screenshot({path:'.build/slides/lecture4/revised-lidar-'+width+'.png',fullPage:true})}
assert.deepEqual(errors,[]);console.log('PASS: WebGL rendering; fixed 360°; returns in all quadrants; pause/step; display/color/envelope/frame controls; presets; all five 3D scenes; scene-first responsive layout');await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
