'use strict';
const D=Math.PI/180, $=s=>document.querySelector(s), fmt=(x,n=2)=>Number(x).toFixed(n);
const I=()=>[[1,0,0],[0,1,0],[0,0,1]];
const mm=(a,b)=>a.map(r=>b[0].map((_,j)=>r.reduce((s,v,k)=>s+v*b[k][j],0)));
function transform(theta,len){const c=Math.cos(theta),s=Math.sin(theta);return [[c,-s,len*c],[s,c,len*s],[0,0,1]]}
function fk(links){let T=I();return links.map(l=>{const angle=l.type==='rotary'?l.q*D:l.angle*D;const length=l.length+(l.type==='slider'?l.q:0);const A=transform(angle,length);T=mm(T,A);return{A,T,x:T[0][2],y:T[1][2],angle:Math.atan2(T[1][0],T[0][0])}})}
function project(p,k){if(p[2]<=0)return null;let x=p[0]/p[2],y=p[1]/p[2],r2=x*x+y*y,f=1+(k.k1||0)*r2;return[k.fx*x*f+k.cx,k.fy*y*f+k.cy]}
function hfov(k,w=800){return (Math.atan(k.cx/k.fx)+Math.atan((w-k.cx)/k.fx))/D}
function rayBox(o,d,b){let near=0,far=Infinity;for(let k=0;k<3;k++){if(Math.abs(d[k])<1e-10){if(o[k]<b.min[k]||o[k]>b.max[k])return Infinity;continue}let a=(b.min[k]-o[k])/d[k],z=(b.max[k]-o[k])/d[k];if(a>z)[a,z]=[z,a];near=Math.max(near,a);far=Math.min(far,z);if(near>far)return Infinity}return near>1e-8?near:far}
// Every visible obstacle surface uses the same cuboids as the range calculation.
const boxes=[];
function obstacle(name,min,max,color){boxes.push({name,min,max,color})}
function car(name,x,y,color,van=false){
 obstacle(name,[x-2,y-.9,.25],[x+2,y+.9,1.0],color);
 obstacle(name,[x-.8,y-.78,1],[x+1.1,y+.78,van?2.5:1.65],van?color:'#496a89');
 for(let dx of [-1.35,1.35])for(let dy of [-.94,.94])obstacle(name,[x+dx-.34,y+dy-.13,0],[x+dx+.34,y+dy+.13,.55],'#172336');
}
car('Car ahead',12,-2,'#eca44a');car('Car behind',-12,2,'#ce6482');car('Delivery van',-5,-17,'#e0ddd1',true);car('Cross traffic',8,18,'#64a4cd');
for(let [x,y,name] of [[19,7,'Pedestrian'],[-9,-7,'Pedestrian behind'],[-17,8,'Pedestrian west']]){
 obstacle(name,[x-.24,y-.18,0],[x+.24,y+.18,.9],'#344c6f');obstacle(name,[x-.32,y-.25,.8],[x+.32,y+.25,1.48],'#26c0af');obstacle(name,[x-.19,y-.19,1.48],[x+.19,y+.19,1.85],'#edc18e');}
obstacle('Building east',[25,10,0],[34,24,9],'#59758c');obstacle('Building west',[-31,-24,0],[-22,-11,7],'#63718e');
obstacle('Building north',[-15,27,0],[1,35,11],'#476b86');obstacle('Rear garage',[-32,11,0],[-24,24,5],'#738191');
obstacle('Front wall',[38,-25,0],[39,7,4],'#8f8290');obstacle('Side wall',[9,-29,0],[31,-28,3],'#8b98ac');
for(let [x,y] of [[6,-9],[-6,10],[16,-8],[-16,10],[9,25],[-20,-8]]){
 obstacle('Lamp post '+x+','+y,[x-.1,y-.1,0],[x+.1,y+.1,4.8],'#99aac1');obstacle('Lamp post '+x+','+y,[x-.15,y-.12,4.6],[x+1.0,y+.12,4.9],'#d7e1e8');}
for(let i=0;i<5;i++)obstacle('Road cone '+(i+1),[3+i*1.8,-4.5,0],[3.45+i*1.8,-4.05,.65],'#f08343');
function scanLidar(v){let pts=[],rays=0;for(let i=0;i<v.channels;i++){const el=(v.lower+(v.upper-v.lower)*i/(v.channels-1))*D;for(let az=-v.hfov/2;(v.hfov===360?az<v.hfov/2-1e-6:az<=v.hfov/2+1e-6);az+=v.step){rays++;const a=az*D,d=[Math.cos(el)*Math.cos(a),Math.cos(el)*Math.sin(a),Math.sin(el)],o=[0,0,v.height];let r=d[2]<0?-v.height/d[2]:Infinity,hit='ground';boxes.forEach((b,j)=>{const q=rayBox(o,d,b);if(q<r){r=q;hit=j}});if(r>=v.min&&r<=v.max){pts.push({p:d.map((x,j)=>o[j]+r*x),r,hit,el:el/D,az})}}}return{pts,rays}}
function fusionPoint(p,yaw,tx,dt,speed){const c=Math.cos(yaw*D),s=Math.sin(yaw*D);let x=p[0],y=p[1]+speed*dt/1000;return[-(s*x+c*y)+tx,1.5-p[2],c*x-s*y]}
const defaults={camera:{fx:600,fy:600,cx:400,cy:250,k1:0},lidar:{upper:15,lower:-25,channels:32,hfov:360,step:1,height:1.8,min:0.5,max:80},calibration:{fx:650,fy:650,cx:400,cy:250,yaw:20,pitch:-15,depth:4},fusion:{yaw:0,tx:0,dt:0,speed:10}};
let state={tab:'arm',links:[{type:'rotary',q:30,length:2,angle:0},{type:'rotary',q:45,length:1.5,angle:0}],...structuredClone(defaults),matrixFrame:2};
const names={arm:'1 · Robot arm',camera:'2 · Camera',lidar:'3 · LiDAR',calibration:'4 · Checkerboard',fusion:'5 · Fusion'};
function slider(id,label,min,max,step,value,unit=''){return `<label class="control"><span>${label}<output id="${id}-out">${fmt(value,step<1?2:0)} ${unit}</output></span><input id="${id}" type="range" data-unit="${unit}" min="${min}" max="${max}" step="${step}" value="${value}" aria-label="${label}"></label>`}
function bind(id,fn){$('#'+id).addEventListener('input',e=>{fn(+e.target.value);draw()})}
function updateOutputs(){document.querySelectorAll('input[type=range]').forEach(e=>{$('#'+e.id+'-out').textContent=e.value+(e.dataset.unit?' '+e.dataset.unit:'')})}
function mount(tab){state.tab=tab;location.hash=tab;document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===tab)));const desc={arm:['Robot arm and local frames','Build a planar chain. Each link frame sits at its distal end, with x along the link and y 90° counterclockwise.'],camera:['Camera intrinsics and image formation','A synthetic street projected through a pinhole camera. The scene and camera pose stay fixed as you change K.'],lidar:['360° LiDAR: a scan around the vehicle','Explore the scene, inspect returns, and change vertical coverage. This spinning LiDAR scans the full circle, including behind the vehicle.'],calibration:['Checkerboard correspondences','Known corner spacing connects board coordinates to measured image pixels. Orange marks are observations, blue rings are predictions.'],fusion:['Camera–LiDAR alignment','Orange points use the correct transform. Blue points use your estimated yaw, lateral translation, and time offset.']};
$('main').innerHTML=`<div class="lesson-heading"><div><span class="eyebrow">EXPERIMENT ${Object.keys(names).indexOf(tab)+1} / 5</span><h2>${desc[tab][0]}</h2><p>${desc[tab][1]}</p></div></div><div class="layout"><section class="controls" aria-label="Experiment controls"></section><section class="visuals"><div class="scene-card"><div class="scene-topline"><span>${tab==='lidar'?'SURROUND SCENE + SIMULATED RETURNS':'INTERACTIVE 3D WORLD'}</span><span>${tab==='lidar'?'Azimuth <b id="sweep-angle">0°</b> · full 360° scan':'Drag to orbit · Scroll to zoom'}</span></div><div id="world-host"></div><div id="scene-tools"></div><div id="scene-settings"></div><div id="scene-caption"></div></div><div id="scene-stats"></div>${tab==='lidar'?'<section id="range-experiment" aria-label="Channels and perception at range"></section><div id="inspection">Click a scene object to inspect its LiDAR returns.</div>':''}<details class="diagnostic" ${tab==='lidar'?'':'open'}><summary>${tab==='arm'?'2D frame diagram':tab==='lidar'?'Elevation cross-section and top-view diagnostics':tab==='calibration'?'Observed and predicted image corners':'Camera image output'}</summary><canvas id="view" width="1000" height="590" aria-label="${desc[tab][0]} visualization"></canvas></details><div class="readout" id="readout" aria-live="polite"></div><div class="prompt" id="prompt"></div><details><summary>Model and interpretation</summary><div id="model"></div></details></section></div>`;
if(tab==='arm')armControls();else standardControls(tab);draw();if(window.FusionScene)FusionScene.mount(tab);}
function armControls(){let h='<div class="actions"><button id="add-r">+ Rotary</button><button id="add-p">+ Sliding</button><button id="add-f">+ Fixed link</button><button id="reset">Reset</button></div><p class="small">Up to 8 links. Lengths and extension are metres. Angles are relative to the parent frame.</p>';
state.links.forEach((l,i)=>{h+=`<div class="joint"><h3>Link ${i+1} · ${l.type}</h3>${slider('len'+i,'Base length',.2,3,.1,l.length,'m')}${l.type==='rotary'?slider('q'+i,'Joint angle',-180,180,1,l.q,'°'):slider('a'+i,'Mount angle',-180,180,1,l.angle,'°')}${l.type==='slider'?slider('q'+i,'Extension',0,2,.05,l.q,'m'):''}<button id="del${i}" ${state.links.length===1?'disabled':''}>Remove link ${i+1}</button></div>`});h+='<label class="control">Inspect transform to frame <select id="matrix-frame">'+state.links.map((l,i)=>`<option value="${i+1}" ${state.matrixFrame===i+1?'selected':''}>Frame ${i+1}</option>`).join('')+'</select></label>';
$('.controls').innerHTML=h;['r','p','f'].forEach(t=>$('#add-'+t).onclick=()=>{if(state.links.length>=8)return;state.links.push({type:{r:'rotary',p:'slider',f:'fixed'}[t],length:1,q:0,angle:0});state.matrixFrame=state.links.length;armControls();draw()});$('#reset').onclick=()=>{state.links=[{type:'rotary',q:30,length:2,angle:0},{type:'rotary',q:45,length:1.5,angle:0}];state.matrixFrame=2;armControls();draw()};
state.links.forEach((l,i)=>{bind('len'+i,v=>l.length=v);if(l.type!=='fixed')bind('q'+i,v=>l.q=v);if(l.type!=='rotary')bind('a'+i,v=>l.angle=v);$('#del'+i).onclick=()=>{state.links.splice(i,1);state.matrixFrame=Math.min(state.matrixFrame,state.links.length);armControls();draw()}});$('#matrix-frame').onchange=e=>{state.matrixFrame=+e.target.value;draw()}}
const specs={camera:[['fx','Horizontal focal length fx',200,1200,10,'px'],['fy','Vertical focal length fy',200,1200,10,'px'],['cx','Principal point cx',150,650,5,'px'],['cy','Principal point cy',100,400,5,'px'],['k1','Radial distortion k1',-.25,.25,.01,'']],lidar:[['upper','Upper elevation',0,40,1,'°'],['lower','Lower elevation',-45,-1,1,'°'],['channels','Number of vertical channels',2,128,1,''],['step','Azimuth step',.5,10,.5,'°'],['height','Sensor height',.5,3,.1,'m'],['min','Minimum range',0,5,.1,'m'],['max','Maximum range',10,80,1,'m']],calibration:[['fx','Estimated focal length',350,1100,10,'px'],['cx','Estimated principal point cx',300,500,5,'px'],['cy','Estimated principal point cy',150,350,5,'px'],['yaw','Board yaw',-55,55,1,'°'],['pitch','Board pitch',-50,50,1,'°'],['depth','Board distance',2.5,7,.1,'m']],fusion:[['yaw','Extrinsic yaw error',-8,8,.1,'°'],['tx','Lateral translation error',-1,1,.02,'m'],['dt','Time offset',-200,200,5,'ms'],['speed','Object lateral speed',0,20,.5,'m/s']]};
function standardControls(tab){let h=specs[tab].map(([id,l,a,b,s,u])=>slider(id,l,a,b,s,state[tab][id],u)).join('');h+='<button id="reset">Reset</button>';if(tab==='camera')h+='<button id="zoom">Double fx and fy</button>';if(tab==='calibration')h+='<button id="fit">Fit K to visible corners</button><p class="small">Simplified fit: board pose is known and fx = fy. Real calibration estimates pose and distortion from multiple views.</p>';if(tab==='fusion')h+='<button id="fault">Introduce a fault</button>';
if(tab==='lidar')h='<div class="fixed-coverage"><b>360°</b><span>Horizontal coverage<br>Full rotation, always on</span></div><h3>Scan presets</h3><div class="actions presets"><button data-preset="street">Street</button><button data-preset="dense">Dense</button><button data-preset="sparse">Sparse</button><button data-preset="blind">Near blind zone</button></div><h3>Sensor geometry</h3>'+h;$('.controls').innerHTML=h;if(tab==='lidar')document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{state.lidar={...structuredClone(defaults.lidar),...({street:{},dense:{channels:64,step:.5},sparse:{channels:8,step:4},blind:{lower:-5}}[b.dataset.preset])};standardControls(tab);draw()});specs[tab].forEach(([id,l,a,b,s,u])=>{$('#'+id).dataset.unit=u;bind(id,v=>{state[tab][id]=v;if(tab==='calibration'&&id==='fx')state.calibration.fy=v})});$('#reset').onclick=()=>{state[tab]=structuredClone(defaults[tab]);standardControls(tab);draw()};if(tab==='camera')$('#zoom').onclick=()=>{state.camera.fx=Math.min(1200,state.camera.fx*2);state.camera.fy=Math.min(1200,state.camera.fy*2);standardControls(tab);draw()};if(tab==='calibration')$('#fit').onclick=()=>{const fit=fitBoard(boardPoints(state.calibration));Object.assign(state.calibration,fit);standardControls(tab);draw()};if(tab==='fusion')$('#fault').onclick=()=>{Object.assign(state.fusion,{yaw:3,tx:.2,dt:80});standardControls(tab);draw()}}
let ctx;
function line(x1,y1,x2,y2,color='#00539f',width=2){ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}
function dot(x,y,r,color){ctx.beginPath();ctx.arc(x,y,r,0,2*Math.PI);ctx.fillStyle=color;ctx.fill()}
function txt(s,x,y,size=17,color='#17324d'){ctx.fillStyle=color;ctx.font=`${size}px Arial`;ctx.fillText(s,x,y)}
function arrow(x,y,ang,len,color,label){let X=x+len*Math.cos(ang),Y=y-len*Math.sin(ang);line(x,y,X,Y,color,2);line(X,Y,X-9*Math.cos(ang-.4),Y+9*Math.sin(ang-.4),color);line(X,Y,X-9*Math.cos(ang+.4),Y+9*Math.sin(ang+.4),color);if(label)txt(label,X+5,Y-3,15,color)}
function draw(){if(!$('#view'))return;ctx=$('#view').getContext('2d');ctx.clearRect(0,0,1000,590);updateOutputs();({arm:drawArm,camera:drawCamera,lidar:drawLidar,calibration:drawCalibration,fusion:drawFusion})[state.tab]();if(window.FusionScene)FusionScene.update()}
function matrixText(A){return A.map(r=>'[ '+r.map(x=>(x<0?'':' ')+fmt(x,3)).join('  ')+' ]').join('\n')}
function drawArm(){const chain=fk(state.links),points=[[0,0],...chain.map(c=>[c.x,c.y])];let max=Math.max(3,...points.flat().map(Math.abs))+.8,minx=Math.min(...points.map(p=>p[0])),maxx=Math.max(...points.map(p=>p[0])),miny=Math.min(...points.map(p=>p[1])),maxy=Math.max(...points.map(p=>p[1])),scale=Math.min(680/(maxx-minx+1),360/(maxy-miny+1)),ox=460-(minx+maxx)*scale/2,oy=315+(miny+maxy)*scale/2;for(let v=-Math.ceil(max);v<=Math.ceil(max);v++){line(ox+v*scale,55,ox+v*scale,555,'#e9eef3',1);line(70,oy-v*scale,850,oy-v*scale,'#e9eef3',1)}
arrow(ox,oy,0,55,'#c43b3b','x₀');arrow(ox,oy,Math.PI/2,55,'#268548','y₀');txt('Base {0}',ox-70,oy+25);let prev=[ox,oy];chain.forEach((c,i)=>{let p=[ox+c.x*scale,oy-c.y*scale];line(...prev,...p,'#00539f',8);dot(...prev,9,state.links[i].type==='slider'?'#d77711':'#00539f');dot(...p,6,'#17324d');arrow(...p,c.angle,43,'#c43b3b','x'+(i+1));arrow(...p,c.angle+Math.PI/2,43,'#268548','y'+(i+1));txt('{'+(i+1)+'}',p[0]-24,p[1]+26,17);prev=p});dot(...prev,11,'#d77711');txt('HAND',prev[0]+16,prev[1]+26,17,'#a94c00');txt('x axes: red    y axes: green    hand: orange',35,30,17);txt('1 grid square = 1 m',35,570,16);const end=chain.at(-1),sel=chain[state.matrixFrame-1];$('#readout').innerHTML=`<strong>Hand in base frame: (${fmt(end.x)}, ${fmt(end.y)}) m</strong> · orientation ${fmt(end.angle/D,1)}°<br>T₀,${chain.length} = ${chain.map((c,i)=>'T'+i+','+(i+1)).join(' × ')}<details open><summary>Frame ${state.matrixFrame}: local and cumulative matrices</summary><pre>Parent ← link\n${matrixText(sel.A)}\nBase ← link\n${matrixText(sel.T)}</pre></details>`;$('#prompt').innerHTML='<strong>Try it:</strong> Set both lengths to 1 m, q₁ = 90°, q₂ = −90°. Predict the hand position before checking. Add a sliding joint and explain which direction it extends.';$('#model').innerHTML='<p>Column vectors. Tᵢ₋₁,ᵢ = Rot(θᵢ) Transₓ(Lᵢ + dᵢ). For rotary joints dᵢ = 0. Fixed and sliding links use a fixed mount angle. The displayed 3×3 matrix represents 2D homogeneous coordinates. p₀ = T₀₁ T₁₂ … Tₙ₋₁,ₙ [0,0,1]ᵀ. No dynamics, collision checking, joint limits beyond the sliders, or inverse kinematics.</p>'}
// Camera drawing uses an 800 × 500 image at an offset within the canvas.
function imageBorder(){ctx.fillStyle='#f4f8fb';ctx.fillRect(100,50,800,500);ctx.strokeStyle='#9cb4c8';ctx.lineWidth=1;ctx.strokeRect(100,50,800,500)}
function pLine(a,b,k,col,width=2){const n=24;let prev=null;for(let j=0;j<=n;j++){const t=j/n,p=project(a.map((v,i)=>v*(1-t)+b[i]*t),k);if(p&&prev)line(prev[0]+100,prev[1]+50,p[0]+100,p[1]+50,col,width);prev=p}}
function wireBox(min,max,k,col){let v=[];for(let i=0;i<8;i++)v.push([i&1?max[0]:min[0],i&2?max[1]:min[1],i&4?max[2]:min[2]]);for(let i=0;i<8;i++)for(let bit of [1,2,4])if(!(i&bit))pLine(v[i],v[i|bit],k,col,3)}
function street(k){imageBorder();ctx.save();ctx.beginPath();ctx.rect(100,50,800,500);ctx.clip();for(let z of [3,5,8,12,20,35,60])pLine([-12,1.5,z],[12,1.5,z],k,'#bdcdda',1);for(let x of [-6,-3,0,3,6])pLine([x,1.5,2],[x,1.5,70],k,x===0?'#d6b347':'#8cabc1',2);wireBox([-2,-.1,9],[0,1.5,13],k,'#d77711');wireBox([2,-.5,17],[2.6,1.5,17.6],k,'#008981');wireBox([-9,-5,24],[-6,1.5,33],k,'#79869b');ctx.restore()}
function drawCamera(){const k=state.camera;street(k);line(k.cx+92,k.cy+50,k.cx+108,k.cy+50,'#bd3838');line(k.cx+100,k.cy+42,k.cx+100,k.cy+58,'#bd3838');txt('Synthetic image • 800 × 500 pixels',100,30,19);txt('Camera axes: X right, Y down, Z forward',100,580,17);const p=project([1,0,10],k);$('#readout').innerHTML=`<strong>Ideal pinhole horizontal FOV: ${fmt(hfov(k),1)}°</strong> · vertical FOV: ${fmt((Math.atan(k.cy/k.fy)+Math.atan((500-k.cy)/k.fy))/D,1)}°<br>Point (1, 0, 10) m projects to (${fmt(p[0])}, ${fmt(p[1])}) px.<pre>K = [ ${k.fx}   0   ${k.cx} ]\n    [ 0   ${k.fy}   ${k.cy} ]\n    [ 0     0     1 ]</pre>`;$('#prompt').innerHTML='<strong>Try it:</strong> Double fx and fy. Then change only cx. Which changes object size? Which shifts the image? Set k₁ ≠ 0 and watch straight road lines bend.';$('#model').innerHTML='<p>u = fₓ X/Z + cₓ, v = fᵧ Y/Z + cᵧ for Z > 0. Radial demo: xᵈ = x(1+k₁r²), yᵈ = y(1+k₁r²). Reported FOV excludes distortion. Changing K here re-renders a fixed synthetic scene. Editing a real camera’s metadata alone does not change captured pixels. Resizing/cropping images requires updating K. No exposure, blur, or full lens model.</p>'}
function drawLidar(){drawRangeExperiment();const v=state.lidar,{pts,rays}=scanLidar(v);const scale=210/v.max,sx=x=>50+x*5,sz=z=>420-z*20,tx=x=>750+x*scale,ty=y=>290-y*scale;
ctx.save();ctx.beginPath();ctx.rect(30,55,450,440);ctx.clip();line(40,sz(0),475,sz(0),'#688aa5');boxes.forEach(b=>{ctx.strokeStyle=b.color;ctx.strokeRect(sx(b.min[0]),sz(b.max[2]),(b.max[0]-b.min[0])*5,(b.max[2]-b.min[2])*20)});for(let i=0;i<v.channels;i++){const a=(v.lower+(v.upper-v.lower)*i/(v.channels-1))*D;let r=a<0?Math.min(v.max,-v.height/Math.sin(a)):v.max;line(sx(0),sz(v.height),sx(r*Math.cos(a)),sz(v.height+r*Math.sin(a)),'#c5dbe9',1)}pts.filter(h=>h.p[0]>=0).forEach(h=>{let c=h.hit==='ground'?'#759eb8':boxes[h.hit].color;dot(sx(h.p[0]),sz(h.p[2]),2,c)});dot(sx(0),sz(v.height),7,'#00539f');ctx.restore();
ctx.save();ctx.beginPath();ctx.rect(525,55,450,470);ctx.clip();line(530,290,975,290,'#e4ebf2');line(750,65,750,515,'#e4ebf2');boxes.forEach(b=>{ctx.strokeStyle=b.color;ctx.strokeRect(tx(b.min[0]),ty(b.max[1]),(b.max[0]-b.min[0])*scale,(b.max[1]-b.min[1])*scale)});pts.forEach(h=>{let c=h.hit==='ground'?'#759eb8':boxes[h.hit].color;dot(tx(h.p[0]),ty(h.p[1]),2,c)});dot(tx(0),ty(0),7,'#00539f');ctx.restore();
txt('SIDE VIEW • x forward / z up',30,30,19);txt('TOP VIEW • x forward / y left',525,30,19);txt('0 m',sx(0),450,15);txt('40 m',sx(40),450,15);txt('80 m',sx(80),450,15);txt('Forward sector; beams beyond the plot are clipped.',30,480,14);txt('Top-view radius: '+v.max+' m',530,535,15);txt('Points show nearest valid returns; light lines show beam elevations.',30,575,17);const blind=v.height/Math.tan(-v.lower*D);$('#readout').innerHTML=`<strong>${pts.length.toLocaleString()} returns / ${rays.toLocaleString()} emitted rays per simulated scan</strong><br>Horizontal FOV 360° · vertical FOV ${v.upper-v.lower}° · beam spacing ${fmt((v.upper-v.lower)/(v.channels-1))}° · lowest beam reaches flat ground at ${fmt(blind)} m.<br>Front car returns: ${pts.filter(h=>h.hit!=='ground'&&boxes[h.hit].name==='Car ahead').length} · rear car returns: ${pts.filter(h=>h.hit!=='ground'&&boxes[h.hit].name==='Car behind').length}`;$('#prompt').innerHTML='<strong>Try it:</strong> Raise the lower elevation toward 0°. What happens to near-ground coverage? Double the channels at the same FOV. Then double the vertical FOV while keeping channel count fixed.';$('#model').innerHTML='<p>x = r cos(φ) cos(θ), y = r cos(φ) sin(θ), z = r sin(φ), then add sensor height. φ is elevation and θ is azimuth. Full 360° horizontal scanning, one nearest return per ray, with minimum and maximum slant range. Scene obstacles use the same cuboids as the ray intersections. The ego car is a mounting reference and is excluded from self-returns. The sweep is slowed for teaching and does not represent hardware scan speed. The lowest-beam ground distance assumes unobstructed flat ground. Hardware beam patterns may be nonuniform. Real rate, reflectivity, noise, weather, and motion are outside this static ideal model.</p>'}
const trueK={fx:800,fy:800,cx:410,cy:245,k1:0};
function boardPoint(x,y,v){const a=v.yaw*D,b=v.pitch*D;return[Math.cos(a)*x+Math.sin(a)*Math.sin(b)*y,Math.cos(b)*y,-Math.sin(a)*x+Math.cos(a)*Math.sin(b)*y+v.depth]}
function boardPoints(v){let a=[];for(let j=0;j<6;j++)for(let i=0;i<9;i++){let p=boardPoint((i-4)*.2,(j-2.5)*.2,v);a.push({p,uv:project(p,trueK)})}return a}
function fitBoard(points){let n=points.length,mx=0,my=0,mu=0,mv=0;points.forEach(({p,uv})=>{mx+=p[0]/p[2]/n;my+=p[1]/p[2]/n;mu+=uv[0]/n;mv+=uv[1]/n});let num=0,den=0;points.forEach(({p,uv})=>{let x=p[0]/p[2]-mx,y=p[1]/p[2]-my;num+=x*(uv[0]-mu)+y*(uv[1]-mv);den+=x*x+y*y});let f=num/den;return{fx:f,fy:f,cx:mu-f*mx,cy:mv-f*my}}
function boardRms(v){const p=boardPoints(v);return Math.sqrt(p.reduce((s,{p,uv})=>{let q=project(p,v);return s+(q[0]-uv[0])**2+(q[1]-uv[1])**2},0)/p.length)}
function drawCalibration(){let v=state.calibration;imageBorder();for(let j=-1;j<6;j++)for(let i=-1;i<9;i++){let corners=[[i,j],[i+1,j],[i+1,j+1],[i,j+1]].map(([x,y])=>project(boardPoint((x-4)*.2,(y-2.5)*.2,v),trueK));ctx.beginPath();corners.forEach((p,k)=>k?ctx.lineTo(p[0]+100,p[1]+50):ctx.moveTo(p[0]+100,p[1]+50));ctx.closePath();ctx.fillStyle=(i+j)%2===0?'#dce2e8':'#536477';ctx.fill()};boardPoints(v).forEach(({p,uv},i)=>{let q=project(p,v);line(uv[0]+100,uv[1]+50,q[0]+100,q[1]+50,'#db7147',1);dot(uv[0]+100,uv[1]+50,3,'#ec8e00');ctx.beginPath();ctx.strokeStyle='#008cdf';ctx.lineWidth=2;ctx.arc(q[0]+100,q[1]+50,5,0,Math.PI*2);ctx.stroke();if(i===0)txt('(0,0,0)',uv[0]+105,uv[1]+45,15)});txt('9 × 6 inner corners • 10 × 7 squares • square size 0.20 m',100,30,18);txt('Orange: observed corners    Blue rings: predicted corners',100,580,18);$('#readout').innerHTML=`<strong>Reprojection RMS: ${fmt(boardRms(v))} px over 54 corners</strong><br>Ground truth for this simulation: fx = fy = 800, cx = 410, cy = 245 px.<br>Board point Pᵢⱼ = (0.20 i, 0.20 j, 0) m, with the board origin at the first inner corner.`;$('#prompt').innerHTML='<strong>Try it:</strong> Adjust focal length to reduce residuals, then fit K. Tilt the board and check the fitted result. Discuss why an actual calibration must also estimate the unknown board pose from many different views.';$('#model').innerHTML='<p>The renderer uses a centered board pose internally, equivalent to translating the first-corner origin before rotation. The fit minimizes squared pixel residuals with known board pose, equal focal lengths, zero distortion, and noise-free corners. It is an illustration of correspondence and residual minimization, not a full camera calibration solver. A real workflow uses multiple tilted views across the image, subpixel corners, lens distortion estimation, and held-out validation. LiDAR generally measures board geometry, not the printed corner grid.</p>'}
function drawFusion(){const k={fx:600,fy:600,cx:400,cy:250};street(k);let err=0,n=0;const v=state.fusion;ctx.save();ctx.beginPath();ctx.rect(100,50,800,500);ctx.clip();for(let x of [10,20,35])for(let y=-1.5;y<=1.5;y+=.3)for(let z of [.2,.7,1.2,1.7]){let p=[x,y,z],a=project(fusionPoint(p,0,0,0,0),k),b=project(fusionPoint(p,v.yaw,v.tx,v.dt,v.speed),k);err+=(a[0]-b[0])**2+(a[1]-b[1])**2;n++;dot(a[0]+100,a[1]+50,3,'#e18816');dot(b[0]+100,b[1]+50,2,'#008bdb')}ctx.restore();txt('Three synthetic moving target planes at 10, 20, and 35 m',100,30,19);txt('Orange: correct projection    Blue: perturbed projection',100,580,18);$('#readout').innerHTML=`<strong>Projection RMS error: ${fmt(Math.sqrt(err/n))} px</strong><br>Lateral motion during time offset: ${fmt(v.speed*v.dt/1000)} m. At 10 m, a 1 m lateral error gives 60 px for fx = 600 px.<br>Nominal mapping: Xc = −Yl, Yc = 1.5 − Zl, Zc = Xl.`;$('#prompt').innerHTML='<strong>Try it:</strong> Introduce a fault, then change one parameter at a time. Compare yaw error across depths with translation error. Set yaw and translation to zero, then use 100 ms and 10 m/s.';$('#model').innerHTML='<p>The nominal LiDAR frame is x forward, y left, z up at ground level. The camera is 1.5 m above it with optical x right, y down, z forward. Estimated yaw rotates the LiDAR point before this axis conversion. Time offset shifts each synthetic target along LiDAR y at a constant speed. These planes illustrate pixel error patterns and are independent of the background street. No real detection, association, occlusion removal, ego-motion deskewing, or calibration optimizer runs here. A synchronized timestamp alone does not correct motion within a LiDAR sweep.</p>'}
Object.entries(names).forEach(([tab,name])=>{const b=document.createElement('button');b.textContent=name;b.dataset.tab=tab;b.setAttribute('aria-selected','false');b.onclick=()=>mount(tab);$('nav').appendChild(b)});
window.Lab={boxes,boardPoint,fk,project,hfov,rayBox,scanLidar,fusionPoint,fitBoard,boardPoints,boardRms,defaults,trueK,state,mount,draw};
window.addEventListener('hashchange',()=>{const tab=location.hash.slice(1);if(names[tab]&&tab!==state.tab)mount(tab)});
mount(names[location.hash.slice(1)]?location.hash.slice(1):'arm');

// Isolated front-facing target experiment: exact ray/plane intersections on the
// same elevation/azimuth sampling grid as the surround scanner, without clutter.
function targetReturns(v,range,width=0.6,height=1.8){
 const hits=[];let rows=0;
 for(let i=0;i<v.channels;i++){
  const el=(v.lower+(v.upper-v.lower)*i/(v.channels-1))*D;let rowHit=false;
  for(let az=-180;az<180-1e-6;az+=v.step){
   const a=az*D;if(Math.cos(a)<=0)continue;
   const r=range/(Math.cos(el)*Math.cos(a)),y=range*Math.tan(a),z=v.height+r*Math.sin(el);
   if(r>=v.min&&r<=v.max&&Math.abs(y)<=width/2+1e-9&&z>=0&&z<=height){hits.push({y,z});rowHit=true;}
  }
  if(rowHit)rows++;
 }
 return {hits,rows};
}
function drawRangeExperiment(){
 const host=$('#range-experiment');if(!host)return;const v=state.lidar;
 if(!host.firstChild){
 host.innerHTML=`<div class="range-heading"><h3>Channels → points → evidence at range</h3><p>Identical 0.6 m wide × 1.8 m tall targets, viewed separately without occlusion. Each panel uses the same physical scale.</p></div><div class="density-controls">${slider('range-channels','Number of channels',2,128,1,v.channels)}${slider('range-step','Horizontal angular step',.5,10,.5,v.step,'°')}<div class="actions">${[8,16,32,64,128].map(n=>`<button data-channels="${n}">${n} channels</button>`).join('')}</div></div><div id="range-summary"></div><canvas id="range-view" width="1050" height="360" aria-label="Point returns on identical targets at 10, 30 and 60 metres"></canvas><p class="small">These are geometric returns, not detector predictions. Zero points means no measurement in this scan; a few points do not guarantee recognition. Discrete beam alignment can make counts jump.</p>`;
 for(const [id,key] of [['range-channels','channels'],['range-step','step']])$('#'+id).oninput=e=>{v[key]=+e.target.value;$('#'+key).value=e.target.value;draw()};
 host.querySelectorAll('[data-channels]').forEach(b=>b.onclick=()=>{state.lidar.channels=+b.dataset.channels;$('#channels').value=state.lidar.channels;draw()});
 }
 // Read current state on each input because presets replace the settings object.
 $('#range-channels').oninput=e=>{state.lidar.channels=+e.target.value;$('#channels').value=e.target.value;draw()};
 $('#range-step').oninput=e=>{state.lidar.step=+e.target.value;$('#step').value=e.target.value;draw()};
 for(const [id,key] of [['range-channels','channels'],['range-step','step']]){$('#'+id).value=v[key];$('#'+id+'-out').textContent=v[key]+(key==='step'?' °':'');}
 host.querySelectorAll('[data-channels]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.channels===v.channels)));
 const spacing=(v.upper-v.lower)/(v.channels-1);
 $('#range-summary').textContent=`${v.channels} channels · ${fmt(spacing)}° vertical spacing · ${Math.ceil(360/v.step).toLocaleString()} azimuth samples/channel · ${(v.channels*Math.ceil(360/v.step)).toLocaleString()} emitted rays/360° scan`;
 const c=$('#range-view').getContext('2d');c.fillStyle='#0a1527';c.fillRect(0,0,1050,360);
 [10,30,60].forEach((range,j)=>{
  const x=j*350+175,top=62,scale=115,result=targetReturns(v,range);
  c.fillStyle='#dbeafa';c.font='bold 21px Arial';c.textAlign='center';c.fillText(range+' m',x,30);
  c.fillStyle='#18354c';c.fillRect(x-.3*scale,top,.6*scale,1.8*scale);c.strokeStyle='#7192ac';c.strokeRect(x-.3*scale,top,.6*scale,1.8*scale);
  c.fillStyle='#57ffce';result.hits.forEach(p=>{c.beginPath();c.arc(x+p.y*scale,top+(1.8-p.z)*scale,3,0,Math.PI*2);c.fill()});
  c.font='bold 18px Arial';c.fillStyle='#57ffce';c.fillText(result.hits.length+' points · '+result.rows+' channels hit',x,298);
  c.font='14px Arial';c.fillStyle='#a8c2d8';c.fillText('Approx. beam gap: '+fmt(range*Math.tan(spacing*D))+' m',x,323);
  c.fillText(range>v.max?'Beyond maximum range ('+v.max+' m)':'At target centre; gaps grow with range',x,346);
 });
 c.textAlign='left';
}
