/* Local Three.js scene layer. Sensor calculations remain in lab.js. */
'use strict';
window.FusionScene=(()=>{
let renderer,scene,camera,root,scanRoot,worldRoot,frameRoot,pointObject,sweepObject,host,tabName,cacheKey='',cloud=[],rayCount=0,selected=null;
const T=window.THREE,rad=Math.PI/180;
let azimuth=-2.35,elevation=.8,distance=57,target=new T.Vector3(1,1,0),playing=true,phase=0,lastTime=0,needsRender=true;
let viewMode='overlay',colorMode='range',showFrames=true,showEnvelope=false,spin=false,labels=[],worldMeshes=[],dragging=null,previousTab='';
const unitCube=new T.BoxGeometry(1,1,1),vec=p=>new T.Vector3(p[0],p[2],-p[1]); // ROS xyz -> Three xyz, right handed
function mat(color,opacity=1){return new T.MeshStandardMaterial({color,roughness:.7,metalness:.15,transparent:opacity<1,opacity})}
function meshBox(min,max,color,parent=root,opacity=1){const m=new T.Mesh(unitCube,mat(color,opacity));m.position.copy(vec(min.map((v,i)=>(v+max[i])/2)));m.material.polygonOffset=true;m.material.polygonOffsetFactor=1;m.material.polygonOffsetUnits=1;m.scale.set(max[0]-min[0],max[2]-min[2],max[1]-min[1]);parent.add(m);return m}
function segment(a,b,color,parent=root,width=1){const g=new T.BufferGeometry().setFromPoints([vec(a),vec(b)]),m=new T.Line(g,new T.LineBasicMaterial({color,transparent:true,opacity:.8,linewidth:width}));parent.add(m);return m}
function cylinder(a,b,r,color,parent=root){const av=vec(a),bv=vec(b),delta=bv.clone().sub(av),g=new T.CylinderGeometry(r,r,delta.length(),18),m=new T.Mesh(g,mat(color));m.position.copy(av.add(bv).multiplyScalar(.5));m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),delta.normalize());parent.add(m);return m}
function label(text,p,color='#e0f4ff',scale=1.8,parent=root){const c=document.createElement('canvas'),measure=c.getContext('2d');measure.font='bold 46px Arial';c.width=Math.max(96,Math.ceil(measure.measureText(text).width+32));c.height=84;const x=c.getContext('2d');x.fillStyle='rgba(7,20,37,.9)';x.fillRect(0,0,c.width,84);x.fillStyle=color;x.font='bold 46px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text,c.width/2,42);const texture=new T.CanvasTexture(c),sprite=new T.Sprite(new T.SpriteMaterial({map:texture,depthTest:false,transparent:true}));sprite.position.copy(vec(p));sprite.scale.set(scale*1.5*c.width/84,scale*1.5,1);parent.add(sprite);return sprite}
function frame(p,a=0,size=1,text='',parent=frameRoot){const c=Math.cos(a),s=Math.sin(a);for(const [d,color] of [[[c,s,0],0xff6569],[[-s,c,0],0x65df9b],[[0,0,1],0x64adff]]){const ar=new T.ArrowHelper(vec(d).normalize(),vec(p),size,color,size*.2,size*.1);parent.add(ar)}if(text)label(text,[p[0],p[1],p[2]+size+.1],'#e4f5ff',size*.3,parent)}
function opticalFrame(p,size=1,text='CAMERA'){const dirs=[[0,-1,0],[0,0,-1],[1,0,0]];dirs.forEach((d,i)=>frameRoot.add(new T.ArrowHelper(vec(d).normalize(),vec(p),size,[0xff6569,0x65df9b,0x64adff][i],size*.2,size*.1)));label(text,[p[0],p[1],p[2]+size+.1],'#e4f5ff',size*.3,frameRoot)}
function clear(group){if(!group)return;while(group.children.length){let c=group.children[0];c.traverse(o=>{if(o.geometry&&o.geometry!==unitCube)o.geometry.dispose();if(o.material){for(let m of Array.isArray(o.material)?o.material:[o.material]){if(m.map)m.map.dispose();m.dispose()}}});group.remove(c)}}
function cameraPose(){camera.position.set(target.x+distance*Math.cos(elevation)*Math.cos(azimuth),target.y+distance*Math.sin(elevation),target.z+distance*Math.cos(elevation)*Math.sin(azimuth));camera.lookAt(target);camera.updateProjectionMatrix();needsRender=true}
function orbit(mode){if(tabName==='arm'){const pts=[[0,0],...Lab.fk(Lab.state.links).map(c=>[c.x,c.y])],xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys);target.set((minx+maxx)/2,(miny+maxy)/2,0);distance=Math.max(7,Math.hypot(maxx-minx,maxy-miny)*2.6)}else if(tabName==='camera'){target.set(14,1,0);distance=44}else if(tabName==='fusion'){target.set(14,1,0);distance=50}else if(tabName==='calibration'){target.set(2,0,0);distance=10}else{target.set(0,0,0);distance=65}if(mode==='top'){elevation=1.55;azimuth=-Math.PI/2}else if(mode==='side'){elevation=.10;azimuth=-Math.PI/2}else{elevation=.8;azimuth=-2.35}cameraPose()}
function init(){if(renderer)return true;try{renderer=new T.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x0a1527);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.45;scene=new T.Scene();scene.fog=new T.Fog(0x0a1527,100,220);camera=new T.PerspectiveCamera(43,1,.02,400);scene.add(new T.HemisphereLight(0xd5ebff,0x31425c,2.1));let light=new T.DirectionalLight(0xffffff,2.5);light.position.set(-15,35,18);scene.add(light);root=new T.Group();scene.add(root);renderer.domElement.id='world3d';renderer.domElement.setAttribute('aria-label','Interactive 3D scene. Drag to orbit, scroll to zoom.');renderer.domElement.tabIndex=0;
renderer.domElement.onpointerdown=e=>{dragging={x:e.clientX,y:e.clientY,moved:0};renderer.domElement.setPointerCapture(e.pointerId)};
renderer.domElement.onpointermove=e=>{if(!dragging)return;const dx=e.clientX-dragging.x,dy=e.clientY-dragging.y;dragging.moved+=Math.abs(dx)+Math.abs(dy);azimuth-=dx*.006;elevation=Math.max(.06,Math.min(1.56,elevation+dy*.005));dragging.x=e.clientX;dragging.y=e.clientY;cameraPose()};
renderer.domElement.onpointerup=e=>{if(dragging&&dragging.moved<6)pick(e);dragging=null};
renderer.domElement.onwheel=e=>{e.preventDefault();distance=Math.max(tabName==='arm'?3:6,Math.min(130,distance*Math.exp(e.deltaY*.001)));cameraPose()};
renderer.domElement.onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')azimuth-=.12;if(e.key==='ArrowRight')azimuth+=.12;if(e.key==='ArrowUp')elevation=Math.min(1.55,elevation+.1);if(e.key==='ArrowDown')elevation=Math.max(.05,elevation-.1);if(e.key==='+')distance*=.9;if(e.key==='-')distance*=1.1;cameraPose()};requestAnimationFrame(animate);return true}catch(e){console.warn('3D view unavailable; using 2D diagnostic view.',e.message);return false}}
function mount(tab){tabName=tab;host=document.querySelector('#world-host');if(!host||!init()){document.body.classList.add('fallback-2d');const d=document.querySelector('.diagnostic');if(d)d.open=true;return}document.body.classList.remove('fallback-2d');host.appendChild(renderer.domElement);cacheKey='';selected=null;playing=true;viewMode='overlay';colorMode='range';showEnvelope=false;showFrames=true;phase=0;spin=false;clear(root);worldRoot=new T.Group();scanRoot=new T.Group();frameRoot=new T.Group();root.add(worldRoot,scanRoot,frameRoot);worldMeshes=[];labels=[];pointObject=null;sweepObject=null;
let controls=document.querySelector('#scene-tools');controls.innerHTML=`<div class="view-options"><button data-view="perspective" aria-label="Perspective view">Perspective</button><button data-view="top" aria-label="Top view">Top</button><button data-view="side" aria-label="Side view">Side</button><button id="home-view">Reset view</button></div><div class="view-options"><button id="spin-scene" aria-pressed="false">Auto orbit</button>${tab==='lidar'?'<button id="scan-play" aria-pressed="true">Pause sweep</button><button id="scan-step">Step 15°</button>':''}</div>`;
controls.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>orbit(b.dataset.view));document.querySelector('#home-view').onclick=()=>orbit('perspective');document.querySelector('#spin-scene').onclick=e=>{spin=!spin;e.target.setAttribute('aria-pressed',spin)};
if(tab==='lidar'){document.querySelector('#scan-play').onclick=e=>{playing=!playing;e.target.textContent=playing?'Pause sweep':'Resume sweep';e.target.setAttribute('aria-pressed',playing)};document.querySelector('#scan-step').onclick=()=>{playing=false;phase=(phase+15*rad)%(2*Math.PI);document.querySelector('#scan-play').textContent='Resume sweep';document.querySelector('#scan-play').setAttribute('aria-pressed','false');needsRender=true}}
let toggles=document.querySelector('#scene-settings');toggles.innerHTML=tab==='lidar'?`<label>Display <select id="display-mode"><option value="overlay">Scene + points</option><option value="points">Point cloud only</option><option value="scene">Scene only</option></select></label><label>Point color <select id="point-color"><option value="range">Range</option><option value="height">Height</option><option value="object">Object</option></select></label><label class="check"><input type="checkbox" id="envelope"> FOV envelope</label><label class="check"><input type="checkbox" id="frames" checked> Sensor frame</label>`:`<label class="check"><input type="checkbox" id="frames" checked> Local frames</label><span class="small">Drag to orbit · Scroll to zoom · Arrow keys to rotate</span>`;
if(tab==='lidar'){document.querySelector('#display-mode').onchange=e=>{viewMode=e.target.value;applyVisibility()};document.querySelector('#point-color').onchange=e=>{colorMode=e.target.value;cacheKey='';update()};document.querySelector('#envelope').onchange=e=>{showEnvelope=e.target.checked;updateEnvelope();needsRender=true}}
document.querySelector('#frames').onchange=e=>{showFrames=e.target.checked;frameRoot.visible=showFrames;needsRender=true};orbit('perspective');resize();update();}
function resize(){if(!host||!renderer)return;const w=host.clientWidth,h=host.clientHeight;if(w<1||h<1)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();needsRender=true}
window.addEventListener('resize',resize);
function ground(){meshBox([-55,-55,-.3],[55,55,-.05],0x1c2b3e,worldRoot);meshBox([-55,-6,-.04],[55,6,-.015],0x26344a,worldRoot);meshBox([-6,-55,-.035],[6,55,-.01],0x26344a,worldRoot);for(let x=-50;x<50;x+=4){meshBox([x,-.05,0],[x+1.8,.05,.012],0xe6c770,worldRoot);meshBox([-.05,x,0],[.05,x+1.8,.012],0xe6c770,worldRoot)}for(let y of [-5.5,5.5])meshBox([-50,y,0],[50,y+.08,.012],0xa8b9cb,worldRoot);let grid=new T.GridHelper(110,22,0x3e6076,0x284155);grid.position.y=.016;worldRoot.add(grid);}
function world(){ground();const B=Lab.boxes;B.forEach((b,i)=>{let m=meshBox(b.min,b.max,b.color,worldRoot);m.userData={objectIndex:i};worldMeshes.push(m)});const groupNames=new Map();B.forEach(b=>{if(!groupNames.has(b.name)){groupNames.set(b.name,b);if(['Car ahead','Car behind','Pedestrian','Delivery van','Building west','Building east'].includes(b.name)){let p=b.min.map((v,i)=>(v+b.max[i])/2);labels.push(label(b.name,[p[0],p[1],b.max[2]+1.2],'#d0e5fa',1.15,worldRoot))}}});}
function lidarWorld(){world();const h=Lab.state.lidar.height;meshBox([-2.1,-.95,0],[2.1,.95,.7],0x334b68,worldRoot,.85);meshBox([-.75,-.8,.7],[1,.8,1.35],0x58718b,worldRoot,.8);cylinder([0,0,1.3],[0,0,h],.09,0x879bb7,worldRoot);cylinder([0,0,h-.13],[0,0,h+.13],.31,0x32e6cc,worldRoot);label('360° LiDAR',[0,0,h+2.1],'#6af4dc',1.0,worldRoot);frame([0,0,h],0,3.5,'LIDAR');}
function cloudColor(h,v){let c=new T.Color();if(colorMode==='object')return c.set(h.hit==='ground'?'#79a5ce':Lab.boxes.find(b=>b.name===Lab.boxes[h.hit].name).color);const t=colorMode==='height'?Math.max(0,Math.min(1,h.p[2]/7)):Math.min(1,h.r/v.max);return c.setHSL(.53-.50*t,.95,.58)}
function updateCloud(){const v=Lab.state.lidar,scan=Lab.scanLidar(v);cloud=scan.pts;rayCount=scan.rays;const positions=[],colors=[];cloud.forEach(h=>{positions.push(...vec(h.p).toArray());colors.push(...cloudColor(h,v).toArray())});const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setAttribute('color',new T.Float32BufferAttribute(colors,3));pointObject=new T.Points(g,new T.PointsMaterial({size:.16,toneMapped:false,vertexColors:true,sizeAttenuation:true,depthTest:true}));scanRoot.add(pointObject);
const rays=new Float32Array(v.channels*6);sweepObject=new T.LineSegments(new T.BufferGeometry(),new T.LineBasicMaterial({color:0x4bffe0,transparent:true,opacity:.45}));sweepObject.geometry.setAttribute('position',new T.BufferAttribute(rays,3));scanRoot.add(sweepObject);updateEnvelope();
const stats=document.querySelector('#scene-stats');const objects=new Set(cloud.filter(p=>p.hit!=='ground').map(p=>Lab.boxes[p.hit].name));stats.innerHTML=`<div><b>360°</b><span>horizontal coverage</span></div><div><b>${cloud.length.toLocaleString()}</b><span>returns per scan</span></div><div><b>${objects.size}</b><span>objects with returns</span></div><div><b>${((v.upper-v.lower)/(v.channels-1)).toFixed(2)}°</b><span>vertical spacing</span></div>`;
let info=document.querySelector('#scene-caption');let legend=document.querySelector('#color-legend');if(!legend){legend=document.createElement('div');legend.id='color-legend';document.querySelector('#scene-settings').after(legend)}legend.innerHTML=colorMode==='object'?'Object colors match the primary surface color. Ground is blue.':`<span>${colorMode==='height'?'0 m height':v.min+' m range'}</span><i></i><span>${colorMode==='height'?'7+ m':v.max+' m'}</span>`;if(selected)inspectObject(selected);info.innerHTML='<span class="dot-key"></span>Full cloud stays visible. The mint fan traces one azimuth at a time. <strong>Click an object to inspect its returns.</strong>';}
function updateEnvelope(){if(!scanRoot)return;const old=scanRoot.getObjectByName('envelope');if(old){scanRoot.remove(old);old.geometry.dispose();old.material.dispose()}if(!showEnvelope||tabName!=='lidar')return;const v=Lab.state.lidar,p=[];for(let el of [v.lower,v.upper]){const r=Math.min(v.max,28),z=v.height+r*Math.sin(el*rad),rho=r*Math.cos(el*rad);for(let i=0;i<120;i++){const a=i*Math.PI/60,b=(i+1)*Math.PI/60;p.push(...vec([rho*Math.cos(a),rho*Math.sin(a),z]).toArray(),...vec([rho*Math.cos(b),rho*Math.sin(b),z]).toArray())}for(let i=0;i<12;i++){let a=i*Math.PI/6;p.push(...vec([0,0,v.height]).toArray(),...vec([rho*Math.cos(a),rho*Math.sin(a),z]).toArray())}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));let lines=new T.LineSegments(g,new T.LineBasicMaterial({color:0x5d9eff,transparent:true,opacity:.32}));lines.name='envelope';scanRoot.add(lines)}
function applyVisibility(){worldRoot.visible=viewMode!=='points';if(pointObject)pointObject.visible=viewMode!=='scene';frameRoot.visible=showFrames;needsRender=true}
function armWorld(){const links=Lab.state.links,chain=Lab.fk(links);const floor=new T.GridHelper(20,20,0x416783,0x233f58);floor.position.y=-.35;worldRoot.add(floor);meshBox([-.5,-.4,-.35],[.5,.4,.12],0x415a78,worldRoot);const at=p=>[p[0],0,p[1]],origins=[[0,0],...chain.map(c=>[c.x,c.y])];
links.forEach((l,i)=>{const start=at(origins[i]),end=at(origins[i+1]),d=end.map((v,j)=>v-start[j]),length=Math.hypot(...d);const col=l.type==='slider'?0x31c6c0:l.type==='fixed'?0x93a9c3:0xf2ad43;cylinder(start,end,.12,col,worldRoot);if(l.type==='slider'){const mid=start.map((v,j)=>v+d[j]*(l.length/length));cylinder(start,mid,.20,0x287f91,worldRoot)}cylinder([start[0],-.18,start[2]],[start[0],.18,start[2]],.23,0x8399b7,worldRoot);frameArm(end,chain[i].angle,.55,'{'+(i+1)+'}');label('Link '+(i+1),[(start[0]+end[0])/2,-.1,(start[2]+end[2])/2+.33],'#e6f3ff',.30,worldRoot)});frameArm([0,0,0],0,.65,'BASE');let e=chain.at(-1),p=at([e.x,e.y]);cylinder(p,[p[0],-.42,p[2]],.09,0xffcf62,worldRoot);for(let sign of [-1,1])meshBox([p[0]-.07,p[1]-.55,p[2]+sign*.2-.04],[p[0]+.22,p[1]-.45,p[2]+sign*.2+.04],0xffcf62,worldRoot);label('HAND',[p[0],-.2,p[2]+.9],'#ffd282',.35,worldRoot);const xs=origins.map(p=>p[0]),ys=origins.map(p=>p[1]),minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys);distance=Math.max(7,Math.hypot(maxx-minx,maxy-miny)*2.6);target.set((minx+maxx)/2,(miny+maxy)/2,0);cameraPose();document.querySelector('#scene-stats').innerHTML=`<div><b>${links.length}</b><span>links</span></div><div><b>${e.x.toFixed(2)} m</b><span>hand x in base</span></div><div><b>${e.y.toFixed(2)} m</b><span>hand y in base</span></div><div><b>${(e.angle/rad).toFixed(1)}°</b><span>hand orientation</span></div>`;document.querySelector('#scene-caption').textContent='Mechanical view of the planar chain. Frames and hand position update with every joint. The grid below shows the same kinematics in 2D.';}
function frameArm(p,a,size,text){let group=new T.Group();frameRoot.add(group);let dirs=[[Math.cos(a),0,Math.sin(a)],[-Math.sin(a),0,Math.cos(a)],[0,-1,0]];dirs.forEach((d,i)=>group.add(new T.ArrowHelper(vec(d).normalize(),vec(p),size,[0xff6569,0x65df9b,0x64adff][i],size*.2,size*.1)));label(text,[p[0],p[1],p[2]+size+.1],'#e4f5ff',.26,group)}
function frustum(k,origin=[0,0,1.5],depth=14,color=0x53cfee){let corners=[[0,0],[800,0],[800,500],[0,500]].map(([u,v])=>[origin[0]+depth,origin[1]-(u-k.cx)*depth/k.fx,origin[2]-(v-k.cy)*depth/k.fy]);for(let i=0;i<4;i++){segment(origin,corners[i],color);segment(corners[i],corners[(i+1)%4],color)}return corners}
function cameraWorld(){ground();for(let b of [{min:[9,0,0],max:[13,2,1.6],color:0xf1a141},{min:[17,-2.6,0],max:[17.6,-2,2],color:0x31bdb7},{min:[24,6,0],max:[33,9,6.5],color:0x657b9e}])meshBox(b.min,b.max,b.color,worldRoot);meshBox([-.5,-.35,1.2],[0,.35,1.8],0x8295ad,worldRoot);cylinder([0,0,1.5],[.25,0,1.5],.2,0x3fc7e9,worldRoot);frustum(Lab.state.camera);opticalFrame([0,0,1.5],2,'CAMERA');const k=Lab.state.camera;document.querySelector('#scene-stats').innerHTML=`<div><b>${Lab.hfov(k).toFixed(1)}°</b><span>horizontal FOV</span></div><div><b>${k.fx} px</b><span>horizontal focal length</span></div><div><b>${k.fy} px</b><span>vertical focal length</span></div><div><b>${k.cx}, ${k.cy}</b><span>principal point</span></div>`;document.querySelector('#scene-caption').textContent='The cyan frustum changes with K. Below, the same street is projected into an 800 × 500 image. Radial distortion affects the image, not this ideal frustum.';}
function boardWorld(){const v=Lab.state.calibration,grid=new T.GridHelper(12,12,0x416783,0x233f58);grid.position.y=-2;worldRoot.add(grid);const geo=new T.BufferGeometry(),vertices=[],colors=[];for(let j=-1;j<6;j++)for(let i=-1;i<9;i++){let cs=[[i,j],[i+1,j],[i+1,j+1],[i,j+1]].map(([x,y])=>{let p=Lab.boardPoint((x-4)*.2,(y-2.5)*.2,v);return vec([p[2],-p[0],-p[1]])});let c=new T.Color((i+j)%2===0?0xf1e9d9:0x192b45);for(let ix of [0,1,2,0,2,3]){vertices.push(...cs[ix].toArray());colors.push(...c.toArray())}}geo.setAttribute('position',new T.Float32BufferAttribute(vertices,3));geo.setAttribute('color',new T.Float32BufferAttribute(colors,3));geo.computeVertexNormals();worldRoot.add(new T.Mesh(geo,new T.MeshStandardMaterial({vertexColors:true,side:T.DoubleSide,roughness:.8})));meshBox([-.3,-.22,-.2],[0,.22,.2],0x6d819e,worldRoot);for(const [i,{p}] of Lab.boardPoints(v).entries()){if(i%8===0)segment([0,0,0],[p[2],-p[0],-p[1]],0x6bcce7,worldRoot)}opticalFrame([0,0,0],.5,'CAMERA');document.querySelector('#scene-stats').innerHTML=`<div><b>54</b><span>inner corners</span></div><div><b>${v.depth.toFixed(1)} m</b><span>board depth</span></div><div><b>${Lab.boardRms(v).toFixed(2)} px</b><span>reprojection RMS</span></div><div><b>0.20 m</b><span>square spacing</span></div>`;document.querySelector('#scene-caption').textContent='Tilt and move the physical board in 3D, then compare observed and predicted corners below. This fit assumes known board pose.';}
function fusionWorld(){ground();for(let x of [10,20,35]){meshBox([x,-1.5,0],[x+.12,1.5,1.8],0xec9d3e,worldRoot,.3);for(let y=-1.5;y<=1.5;y+=.3)for(let z of [.2,.7,1.2,1.7]){let p=[x,y,z];let m=new T.Mesh(new T.SphereGeometry(.08,5,5),new T.MeshBasicMaterial({color:0xf7b954}));m.position.copy(vec(p));worldRoot.add(m)}label(x+' m',[x,0,3],'#e6f1ff',.45,worldRoot)}frame([0,0,0],0,2,'LIDAR');frustum({fx:600,fy:600,cx:400,cy:250},[0,0,1.5],20);const v=Lab.state.fusion;document.querySelector('#scene-stats').innerHTML=`<div><b>${v.yaw.toFixed(1)}°</b><span>yaw error</span></div><div><b>${v.tx.toFixed(2)} m</b><span>translation error</span></div><div><b>${v.dt} ms</b><span>time offset</span></div><div><b>${(v.speed*v.dt/1000).toFixed(2)} m</b><span>motion mismatch</span></div>`;document.querySelector('#scene-caption').textContent='Reference target planes at three depths. The projection below shows the effect of estimated geometry and timing errors.';}
function update(){if(!renderer||!host?.isConnected)return;const key=JSON.stringify({tab:tabName,links:Lab.state.links,values:Lab.state[tabName],colorMode});if(cacheKey===key)return;cacheKey=key;clear(root);worldRoot=new T.Group();scanRoot=new T.Group();frameRoot=new T.Group();root.add(worldRoot,scanRoot,frameRoot);worldMeshes=[];pointObject=null;sweepObject=null;if(tabName==='lidar'){lidarWorld();updateCloud()}if(tabName==='arm')armWorld();if(tabName==='camera')cameraWorld();if(tabName==='calibration')boardWorld();if(tabName==='fusion')fusionWorld();previousTab=tabName;applyVisibility();resize();needsRender=true;}
function inspectObject(name){const pts=cloud.filter(p=>p.hit!=='ground'&&Lab.boxes[p.hit].name===name);selected=name;document.querySelector('#inspection').innerHTML=`<strong>${name}</strong> · ${pts.length} returns${pts.length?' · nearest '+Math.min(...pts.map(p=>p.r)).toFixed(2)+' m':''}<br><span>Returns come from the first surface each beam reaches. Nearby objects can hide surfaces behind them.</span>`}
function pick(e){if(tabName!=='lidar')return;const rect=renderer.domElement.getBoundingClientRect(),mouse=new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),r=new T.Raycaster();r.setFromCamera(mouse,camera);let hits=r.intersectObjects(worldMeshes);if(!hits.length){selected=null;document.querySelector('#inspection').innerHTML='Click a scene object to inspect its LiDAR returns.';return}inspectObject(Lab.boxes[hits[0].object.userData.objectIndex].name)}
function animate(time){requestAnimationFrame(animate);if(!renderer||!host?.isConnected||document.hidden)return;let dt=lastTime?Math.min(.06,(time-lastTime)/1000):0;lastTime=time;if(spin){azimuth+=dt*.15;cameraPose()}if(tabName==='lidar'&&sweepObject){if(playing){phase=(phase+dt*.75)%(Math.PI*2);needsRender=true}const v=Lab.state.lidar,a=sweepObject.geometry.attributes.position;for(let i=0;i<v.channels;i++){let el=(v.lower+(v.upper-v.lower)*i/(v.channels-1))*rad,d=[Math.cos(el)*Math.cos(phase),Math.cos(el)*Math.sin(phase),Math.sin(el)],o=[0,0,v.height],r=d[2]<0?-v.height/d[2]:Infinity;Lab.boxes.forEach(b=>r=Math.min(r,Lab.rayBox(o,d,b)));r=Math.min(v.max,r);let end=o.map((x,j)=>x+r*d[j]);let from=vec(o),to=vec(end);a.setXYZ(i*2,from.x,from.y,from.z);a.setXYZ(i*2+1,to.x,to.y,to.z)}a.needsUpdate=true;sweepObject.geometry.computeBoundingSphere();let n=document.querySelector('#sweep-angle');if(n)n.textContent=(phase/rad).toFixed(0)+'°';}if(needsRender){renderer.render(scene,camera);needsRender=false}}
return{mount,update,resize,getStatus:()=>({ready:!!renderer,tab:tabName,returns:cloud.length,rays:rayCount,phase:phase/rad,playing,selected,viewMode,colorMode})};})();
