const {chromium}=require('/home/william/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),E=require('../../../2026/Labs/Localization/engine.js');
const root=path.resolve('.build/slides/lecture5');
(async()=>{
 const a=[[1,2],[3,1],[-1,2],[4,5]],t=[2,-3,.7],b=a.map(p=>E.transform(p,t)),f=E.fitRigid(a,b);f.forEach((v,i)=>assert(Math.abs(v-t[i])<1e-10));
 const truth=[4.8,3.7,.2],scan=E.scan(truth),map=E.mapPoints(),g=E.grid(map);for(const mode of ['icp','ndt']){let pose=[5.6,3.1,.4094],old=mode==='ndt'?E.ndtCost(scan,g,pose):Infinity;for(let i=0;i<45;i++){const r=E[mode](scan,mode==='icp'?map:g,pose);pose=r.pose;if(mode==='ndt'){assert(r.cost<=old+1e-12);old=r.cost;}}assert(Math.hypot(pose[0]-truth[0],pose[1]-truth[1])<.06);assert(Math.abs(E.wrap(pose[2]-truth[2]))<.03);}
 assert.equal(E.icp(scan,map,[100,100,0],.1).status,'Too few correspondences');assert(E.likelihood(scan,truth)>E.likelihood(scan,[2,2,1]));assert(E.kldRequired(20,.03)>E.kldRequired(20,.2));
 const pf=new E.ParticleFilter();pf.weight(E.scan(truth,24));assert(Math.abs(pf.particles.reduce((s,p)=>s+p.w,0)-1)<1e-12);const oldSet=new Set(pf.particles.map(p=>JSON.stringify(p.t)));pf.resample();assert(pf.particles.length>=150&&pf.particles.length<=800);assert(pf.particles.every(p=>oldSet.has(JSON.stringify(p.t))));
 const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/google-chrome'}),page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**',r=>r.abort());await page.goto('file://'+path.resolve('2026/Labs/Localization/index.html'));
 const shot=async n=>{await page.locator('#view').screenshot({path:root+'/assets/'+n+'.png'});};
 const frames=async(name,count,stride=1)=>{fs.mkdirSync(root+'/frames/'+name,{recursive:true});for(let i=0;i<count;i++){await page.locator('#view').screenshot({path:root+`/frames/${name}/${String(i).padStart(3,'0')}.png`});for(let j=0;j<stride;j++)await page.click('#step');}};
 await shot('icp-start');await frames('icp-alignment',26);await shot('icp-fit');assert(await page.evaluate(()=>Lab.error)<.08);
 await page.selectOption('#scenario','far');await frames('icp-poor-guess',26);await shot('icp-failure');console.log('ICP poor guess',await page.evaluate(()=>({error:Lab.error,angle:Lab.angleError})));
 await page.click('[data-mode=amcl]');await page.selectOption('#scenario','near');await shot('amcl-prior');await frames('amcl-cycle',25);await shot('amcl-localized');console.log('AMCL near',await page.evaluate(()=>({error:Lab.error,angle:Lab.angleError,n:Lab.pf.particles.length})));
 assert(await page.evaluate(()=>Lab.error)<.55);await page.click('#kidnap');await shot('amcl-kidnap');await frames('amcl-kidnapped',10);await page.click('#global');assert.equal(await page.evaluate(()=>Lab.pf.particles.length),800);await frames('amcl-global',31);await shot('amcl-global');
 await page.click('[data-mode=ndt]');await page.selectOption('#scenario','near');await shot('ndt-grid');await frames('ndt-alignment',30);await shot('ndt-fit');assert(await page.evaluate(()=>Lab.error)<.08);await page.selectOption('#cell','2');await shot('ndt-coarse');await frames('ndt-coarse',25);
 await page.click('#play');assert.equal(await page.locator('#play').innerText(),'Pause');await page.click('#play');await page.click('#reset');assert.equal(await page.evaluate(()=>Lab.iteration),0);
 await page.screenshot({path:root+'/demo-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});for(const mode of ['icp','amcl','ndt']){await page.click(`[data-mode=${mode}]`);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.click('#step');}await page.screenshot({path:root+'/demo-mobile.png',fullPage:true});assert.deepEqual(errors,[]);await browser.close();console.log('PASS: rigid fit, ICP/NDT convergence, NDT monotonic cost, correspondence failure, sensor likelihood, KLD bound, normalized weights, actual resampling, UI controls, offline load, mobile, no JS errors.');
})().catch(e=>{console.error(e);process.exit(1)});
