const {chromium}=require('/home/william/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const base=(process.argv[2]||'http://127.0.0.1:8768/').replace(/\/?$/,'/');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/google-chrome'}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
assert((await page.goto(base)).ok());assert.equal(await page.locator('.choices>.choice').count(),3);for(const route of ['perception/','sensor-fusion/','localization/']){assert((await page.goto(base+route)).ok());assert.equal(await page.getByRole('link',{name:'All course demos',exact:true}).count(),1);await page.getByRole('link',{name:'All course demos',exact:true}).click();assert.equal(await page.locator('h1').innerText(),'Interactive demos');}
await page.goto(base+'localization/#icp');await page.waitForFunction(()=>window.Lab?.mode==='icp');for(let i=0;i<30;i++)await page.click('#step');assert(await page.evaluate(()=>Lab.error)<.06);await page.selectOption('#scenario','far');for(let i=0;i<30;i++)await page.click('#step');assert(await page.evaluate(()=>Lab.error)>1);
await page.click('[data-mode=amcl]');await page.selectOption('#scenario','near');await page.uncheck('#adaptive');for(let i=0;i<3;i++)await page.click('#step');assert.equal(await page.evaluate(()=>Lab.pf.particles.length),800);await page.check('#adaptive');for(let i=0;i<6;i++)await page.click('#step');assert(await page.evaluate(()=>Lab.pf.particles.length)<800);const before=await page.evaluate(()=>Lab.pf.particles.map(p=>p.t));await page.click('#kidnap');assert.deepEqual(await page.evaluate(()=>Lab.pf.particles.map(p=>p.t)),before);await page.click('#global');assert.equal(await page.evaluate(()=>Lab.pf.particles.length),800);
await page.click('[data-mode=ndt]');await page.selectOption('#scenario','near');const n1=await page.evaluate(()=>Lab.grid.cells.length);await page.selectOption('#cell','2');assert.notEqual(await page.evaluate(()=>Lab.grid.cells.length),n1);await page.selectOption('#cell','1');for(let i=0;i<35;i++)await page.click('#step');assert(await page.evaluate(()=>Lab.error)<.06);
await page.setViewportSize({width:390,height:844});for(const route of ['','localization/']){await page.goto(base+route);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}await page.screenshot({path:'.build/slides/lecture5/site-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'.build/slides/lecture5/site-desktop.png',fullPage:true});
assert((await page.goto(base+'localization/gifs/')).ok());const gifLinks=await page.locator('a[download]').evaluateAll(as=>as.map(a=>a.href));assert.equal(gifLinks.length,7);for(const url of gifLinks){const r=await page.request.get(url);assert(r.ok());assert.equal((await r.body()).subarray(0,3).toString(),'GIF');}
const hashes={};for(const name of ['Lecture 5 Localization for Autonomous Driving.pptx','Lecture5_Localization.zip']){const response=await page.request.get(base+'downloads/'+encodeURIComponent(name));assert(response.ok());const bytes=await response.body();const local=fs.readFileSync('2026/'+(name.endsWith('.pptx')?'Presentations/':'Data/')+name);assert(bytes.equals(local));hashes[name]=crypto.createHash('sha256').update(bytes).digest('hex');}assert.deepEqual(errors,[]);console.log(JSON.stringify({base,verified:'three portal routes, return navigation, live ICP failure/success, AMCL fixed/adaptive sampling, kidnap state separation, NDT resolution/convergence, mobile width, seven GIFs, exact PPTX/ZIP bytes, zero JS errors',hashes},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
