'use strict';
const E=Localization,$=s=>document.querySelector(s),canvas=$('#view'),ctx=canvas.getContext('2d');
const map=E.mapPoints();let timer=null;
const Lab={mode:'icp',truth:[4.8,3.7,.2],pose:[],points:[],iteration:0,phase:0,message:'',grid:E.grid(map,1)};
const descriptions={icp:['Iterative Closest Point','Each step finds the nearest map points, solves a rigid rotation and translation, and transforms the scan. A wrong initial guess can settle at a wrong alignment.','Try Nearby, then Poor initial guess. A tiny correspondence gate can leave too few matches. The line segments show the correspondences used in the last update.'],amcl:['Adaptive Monte Carlo Localization','Particles are competing (x, y, yaw) hypotheses. Motion spreads them, measurements reweight them, and resampling concentrates computation. KLD adapts the number of samples to occupied pose bins.','Step cycles through motion → measurement → KLD resampling. Purple arrow length shows weight before resampling. Kidnap changes the true pose without informing the filter; use Global reinitialize to recover.'],ndt:['Normal Distributions Transform','Each occupied cell summarizes map points with a mean and covariance. Orange scan points are scored against these distributions. Ellipses show one standard deviation of map geometry, not vehicle pose uncertainty.','Compare 0.5 m, 1 m, and 2 m cells. Each step searches nearby pose values for a lower Gaussian cost. Poor initialization can stall or align incorrectly.']};
function stop(){clearInterval(timer);timer=null;$('#play').textContent='Play';}
function reset(){stop();Lab.truth=[4.8,3.7,.2];Lab.previousTruth=[...Lab.truth];Lab.points=E.scan(Lab.truth);Lab.pose=[Lab.truth[0]+Number($('#dx').value),Lab.truth[1]-.6,Lab.truth[2]+Number($('#da').value)*Math.PI/180];Lab.iteration=0;Lab.phase=0;Lab.pairs=[];Lab.message='Initial guess';Lab.selection=null;Lab.pf=new E.ParticleFilter($('#scenario').value==='far');Lab.grid=E.grid(map,Number($('#cell').value));$('#dxv').textContent=Number($('#dx').value).toFixed(1);$('#dav').textContent=$('#da').value;draw();}
function setMode(mode){Lab.mode=['icp','amcl','ndt'].includes(mode)?mode:'icp';location.hash=Lab.mode;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===Lab.mode)));$('#title').textContent=descriptions[Lab.mode][0];$('#explanation').textContent=descriptions[Lab.mode][1];$('#instruction').textContent=descriptions[Lab.mode][2];$('#registration').hidden=Lab.mode==='amcl';$('#particle').hidden=Lab.mode!=='amcl';$('#gate-label').hidden=Lab.mode!=='icp';$('#cell-label').hidden=Lab.mode!=='ndt';$('#kidnap').hidden=$('#global').hidden=Lab.mode!=='amcl';reset();if(typeof interactionMode==='function')interactionMode();}
function step(){Lab.selection=null;if(Lab.mode==='icp'){const r=E.icp(Lab.points,map,Lab.pose,Number($('#gate').value));Object.assign(Lab,r);Lab.message=r.status;}else if(Lab.mode==='ndt'){const r=E.ndt(Lab.points,Lab.grid,Lab.pose);Object.assign(Lab,r);Lab.message=r.status;}else{if(Lab.phase===0){const u=E.ray(Lab.truth,0)>.35?[.18,0,.045]:[0,0,.2],xy=E.transform(u,Lab.truth);Lab.truth=[xy[0],xy[1],E.wrap(Lab.truth[2]+u[2])];Lab.pf.predict(u,Number($('#motion-noise').value));Lab.points=typeof captureScan==='function'?captureScan():E.scan(Lab.truth,24);}else if(Lab.phase===1)Lab.pf.weight(Lab.points,Number($('#sigma').value));else Lab.pf.resample(Number($('#epsilon').value),$('#adaptive').checked);Lab.message=Lab.pf.stage;Lab.phase=(Lab.phase+1)%3;}Lab.iteration++;draw();}
function pos(p){return[85+p[0]*59,565-p[1]*59];}
function line(a,b,color,width=1){a=pos(a);b=pos(b);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
function dot(p,color,r=3){const[x,y]=pos(p);ctx.beginPath();ctx.arc(x,y,r,0,2*Math.PI);ctx.fillStyle=color;ctx.fill();}
function arrow(p,color,len=.42,width=3){const end=[p[0]+len*Math.cos(p[2]),p[1]+len*Math.sin(p[2])];line(p,end,color,width);for(const sign of [-1,1])line(end,[end[0]-Math.min(.13,len*.4)*Math.cos(p[2]+sign*.6),end[1]-Math.min(.13,len*.4)*Math.sin(p[2]+sign*.6)],color,width);}
function draw(){ctx.fillStyle='#f8fbfd';ctx.fillRect(0,0,960,650);ctx.font='19px Arial';ctx.fillStyle='#17324d';ctx.fillText(`${Lab.mode.toUpperCase()} · ${Lab.message} · step ${Lab.iteration}`,25,30);ctx.font='15px Arial';ctx.fillText('Known map · 1 gray grid square = 1 m',25,55);for(let x=0;x<=12;x++)line([x,0],[x,8],'#e1e9ef');for(let y=0;y<=8;y++)line([0,y],[12,y],'#e1e9ef');for(const[a,b]of E.walls)line(a,b,'#687c8b',3);
if(Lab.mode==='ndt'){for(const c of Lab.grid.cells){const tr=(c.xx+c.yy)/2,d=Math.sqrt(((c.xx-c.yy)/2)**2+c.xy*c.xy),l1=Math.sqrt(tr+d)*59,l2=Math.sqrt(Math.max(.001,tr-d))*59,angle=-.5*Math.atan2(2*c.xy,c.xx-c.yy);ctx.beginPath();ctx.ellipse(...pos(c.mu),l1,l2,angle,0,2*Math.PI);ctx.fillStyle='#008b8b24';ctx.fill();ctx.strokeStyle='#008b8b';ctx.lineWidth=1.7;ctx.stroke();}for(let x=0;x<=12;x+=Lab.grid.size)line([x,0],[x,8],'#008b8b38');for(let y=0;y<=8;y+=Lab.grid.size)line([0,y],[12,y],'#008b8b38');}
let estimate=Lab.pose;if(Lab.mode==='amcl'){estimate=Lab.pf.estimate();const max=Math.max(...Lab.pf.particles.map(p=>p.w));for(const p of Lab.pf.particles){const strength=Math.sqrt(p.w/max);arrow(p.t,`rgba(130,72,174,${.12+.75*strength})`,.07+.32*strength,1.3);}if(Lab.pf.stage==='Measurement weights'){const best=Lab.pf.particles.reduce((a,b)=>a.w>b.w?a:b);for(const p of Lab.points)dot(E.transform(p,best.t),'#d97816',4);}}else{for(const p of map)dot(p,'#61788a',1.3);for(const[a,b]of Lab.pairs||[])line(a,b,'#c8762144');for(const p of Lab.points)dot(E.transform(p,Lab.pose),'#d97816',3);}
const[x,y]=pos(Lab.truth);ctx.beginPath();ctx.arc(x,y,12,0,2*Math.PI);ctx.strokeStyle='#07805d';ctx.lineWidth=3;ctx.stroke();arrow(Lab.truth,'#07805d',.5);arrow(estimate,'#00539f',.65,4);
const error=Math.hypot(estimate[0]-Lab.truth[0],estimate[1]-Lab.truth[1]),angle=Math.abs(E.wrap(estimate[2]-Lab.truth[2]))*180/Math.PI;
let detail=Lab.mode==='icp'?`All-scan nearest-point RMSE: ${Math.sqrt(Lab.points.reduce((s,p)=>s+E.nearest(E.transform(p,Lab.pose),map).d,0)/Lab.points.length).toFixed(3)} m · Matches: ${(Lab.pairs||[]).length}`:Lab.mode==='ndt'?`Gaussian cost: ${E.ndtCost(Lab.points,Lab.grid,Lab.pose).toFixed(3)} · Valid cells: ${Lab.grid.cells.length}`:`Particles: ${Lab.pf.particles.length} · Last measurement ESS: ${Lab.pf.measured?Lab.pf.ess.toFixed(1):'—'} · Last resample bins: ${Lab.pf.bins}`;
$('#metrics').textContent=`${Lab.message}. ${detail}. Pose error (truth available only in simulation): ${error.toFixed(2)} m / ${angle.toFixed(1)}°.`;
ctx.fillStyle='#17324d';ctx.font='16px Arial';ctx.fillText(detail,25,622);Lab.error=error;Lab.angleError=angle;if(typeof interactionDraw==='function')interactionDraw();
}
Object.assign(Lab,{setMode,reset,step,draw,stop,map});window.Lab=Lab;
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#step').onclick=step;$('#reset').onclick=reset;$('#play').onclick=()=>{if(timer)stop();else{timer=setInterval(step,450);$('#play').textContent='Pause';}};
$('#scenario').onchange=()=>{const far=$('#scenario').value==='far';$('#dx').value=far?3.5:.8;$('#da').value=far?75:12;reset();};for(const id of ['dx','da','cell'])$('#'+id).oninput=reset;
$('#kidnap').onclick=()=>{stop();Lab.truth=[9,2,-1.5];Lab.points=typeof captureScan==='function'?captureScan():E.scan(Lab.truth,24);Lab.phase=1;Lab.message='Kidnapped: filter was not informed';draw();};$('#global').onclick=()=>{stop();Lab.pf=new E.ParticleFilter(true,17);Lab.phase=1;Lab.message='Uniform global prior';draw();};window.addEventListener('hashchange',()=>{if(location.hash.slice(1)!==Lab.mode)setMode(location.hash.slice(1));});setMode(location.hash.slice(1)||'icp');
