/* Deterministic, dependency-free 2D teaching implementations. Units: m and rad. */
(function(root){
'use strict';
const TAU=2*Math.PI, wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
function rng(seed=41){return()=>{seed=(1664525*seed+1013904223)>>>0;return(seed+.5)/4294967296;};}
function normal(r){return Math.sqrt(-2*Math.log(r()))*Math.cos(TAU*r());}
const walls=[[[0,0],[12,0]],[[12,0],[12,8]],[[12,8],[0,8]],[[0,8],[0,0]],[[3,0],[3,3]],[[7,5],[12,5]],[[7,5],[7,7]],[[5,2],[6.5,2]]];
function transform(p,t){const c=Math.cos(t[2]),s=Math.sin(t[2]);return[c*p[0]-s*p[1]+t[0],s*p[0]+c*p[1]+t[1]];}
function inverse(p,t){return transform([p[0]-t[0],p[1]-t[1]],[0,0,-t[2]]);}
function mapPoints(){const r=rng(9),out=[];for(const[a,b]of walls){const n=Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])/.07);for(let i=0;i<=n;i++)out.push([a[0]+(b[0]-a[0])*i/n+.025*normal(r),a[1]+(b[1]-a[1])*i/n+.025*normal(r)]);}return out;}
function ray(t,a){const dx=Math.cos(t[2]+a),dy=Math.sin(t[2]+a);let best=20;for(const[p,q]of walls){const sx=q[0]-p[0],sy=q[1]-p[1],den=dx*sy-dy*sx;if(Math.abs(den)<1e-9)continue;const px=p[0]-t[0],py=p[1]-t[1],d=(px*sy-py*sx)/den,u=(px*dy-py*dx)/den;if(d>0&&u>=0&&u<=1)best=Math.min(best,d);}return best;}
function scan(t,n=72){return Array.from({length:n},(_,i)=>{const a=i*TAU/n,d=ray(t,a);return[d*Math.cos(a),d*Math.sin(a)];});}
function nearest(p,map){let d=Infinity,q=null;for(const m of map){const v=(m[0]-p[0])**2+(m[1]-p[1])**2;if(v<d){d=v;q=m;}}return{q,d};}
function fitRigid(a,b){const mean=v=>v.reduce((s,p)=>[s[0]+p[0]/v.length,s[1]+p[1]/v.length],[0,0]),ca=mean(a),cb=mean(b);let dot=0,cross=0;for(let i=0;i<a.length;i++){const x=a[i][0]-ca[0],y=a[i][1]-ca[1],u=b[i][0]-cb[0],v=b[i][1]-cb[1];dot+=x*u+y*v;cross+=x*v-y*u;}const theta=Math.atan2(cross,dot),rc=transform(ca,[0,0,theta]);return[cb[0]-rc[0],cb[1]-rc[1],theta];}
function icp(points,map,pose,gate=2){const src=[],dst=[],pairs=[];for(const p of points){const x=transform(p,pose),n=nearest(x,map);if(n.d<=gate*gate){src.push(x);dst.push(n.q);pairs.push([x,n.q]);}}if(src.length<3)return{pose:[...pose],pairs,status:'Too few correspondences',rmse:null};const delta=fitRigid(src,dst),xy=transform(pose,delta),next=[xy[0],xy[1],wrap(pose[2]+delta[2])];const rmse=Math.sqrt(points.reduce((s,p)=>s+nearest(transform(p,next),map).d,0)/points.length);return{pose:next,pairs,rmse,status:Math.hypot(delta[0],delta[1])+Math.abs(delta[2])<1e-5?'Stationary solution':'Updated pose'};}
function grid(map,size=1){const buckets=new Map();for(const p of map){const k=`${Math.floor(p[0]/size)},${Math.floor(p[1]/size)}`;if(!buckets.has(k))buckets.set(k,[]);buckets.get(k).push(p);}const cells=[];for(const[k,ps]of buckets){if(ps.length<5)continue;const mu=ps.reduce((s,p)=>[s[0]+p[0]/ps.length,s[1]+p[1]/ps.length],[0,0]);let xx=.012,xy=0,yy=.012;for(const p of ps){xx+=(p[0]-mu[0])**2/(ps.length-1);xy+=(p[0]-mu[0])*(p[1]-mu[1])/(ps.length-1);yy+=(p[1]-mu[1])**2/(ps.length-1);}const det=xx*yy-xy*xy;cells.push({k:k.split(',').map(Number),mu,xx,xy,yy,inv:[yy/det,-xy/det,xx/det],n:ps.length});}return{cells,size};}
function ndtCost(points,g,t){let score=0;for(const p of points){const x=transform(p,t),gx=Math.floor(x[0]/g.size),gy=Math.floor(x[1]/g.size);let best=0;for(const c of g.cells){if(Math.abs(c.k[0]-gx)>1||Math.abs(c.k[1]-gy)>1)continue;const dx=x[0]-c.mu[0],dy=x[1]-c.mu[1],m=c.inv[0]*dx*dx+2*c.inv[1]*dx*dy+c.inv[2]*dy*dy;best=Math.max(best,Math.exp(-.5*m));}score-=Math.log(.02+.98*best);}return score/points.length;}
function ndt(points,g,pose,step=.2){let next=[...pose],cost=ndtCost(points,g,next);for(const scale of [1,.4,.12])for(let axis=0;axis<3;axis++){let winner=next;for(const sign of [-1,1]){const t=[...next];t[axis]+=sign*step*scale*(axis===2?.22:1);const c=ndtCost(points,g,t);if(c<cost){cost=c;winner=t;}}next=winner;}return{pose:next,cost,status:next.every((v,i)=>v===pose[i])?'Stationary solution':'Updated pose'};}
function wallDistance(p){let best=Infinity;for(const[a,b]of walls){const dx=b[0]-a[0],dy=b[1]-a[1],u=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy)));best=Math.min(best,Math.hypot(p[0]-a[0]-u*dx,p[1]-a[1]-u*dy));}return best;}
function likelihood(points,t,sigma=.25){if(t[0]<=0||t[0]>=12||t[1]<=0||t[1]>=8)return-1e5;return points.reduce((s,p)=>{const d=wallDistance(transform(p,t));return s+Math.log(.95*Math.exp(-d*d/(2*sigma*sigma))+.05/20);},0);}
function kldRequired(k,eps=.08,z=2.326){if(k<=1)return 800;const a=1-2/(9*(k-1))+z*Math.sqrt(2/(9*(k-1)));return Math.ceil((k-1)/(2*eps)*a**3);}
class ParticleFilter{
 constructor(global=false,seed=7){this.r=rng(seed);this.particles=Array.from({length:800},()=>({t:global?[.1+11.8*this.r(),.1+7.8*this.r(),TAU*this.r()-Math.PI]:[4.6+1.1*normal(this.r),3.7+1.1*normal(this.r),.2+.45*normal(this.r)],w:1/800}));this.stage='Prior';this.ess=800;this.bins=0;}
 predict(u=[.3,0,.08],noise=.06){for(const p of this.particles){const xy=transform([u[0]+noise*normal(this.r),u[1]+noise*normal(this.r)],p.t);p.t=[xy[0],xy[1],wrap(p.t[2]+u[2]+noise*.5*normal(this.r))];}this.stage='Motion prediction';}
 weight(points,sigma=.25){const logs=this.particles.map(p=>Math.log(Math.max(p.w,1e-300))+likelihood(points,p.t,sigma)),max=Math.max(...logs);let sum=0;this.particles.forEach((p,i)=>{p.w=Math.exp(logs[i]-max);sum+=p.w;});this.particles.forEach(p=>p.w/=sum);this.ess=1/this.particles.reduce((s,p)=>s+p.w*p.w,0);this.measured=true;this.stage='Measurement weights';}
 resample(eps=.08,adaptive=true){const cdf=[];let acc=0;for(const p of this.particles){acc+=p.w;cdf.push(acc);}const out=[],bins=new Set();let needed=800;while(out.length<800&&(out.length<150||out.length<needed)){const u=this.r();let lo=0,hi=cdf.length-1;while(lo<hi){const mid=(lo+hi)>>1;if(cdf[mid]<u)lo=mid+1;else hi=mid;}const t=[...this.particles[lo].t];out.push({t,w:0});bins.add(`${Math.floor(t[0]/.5)},${Math.floor(t[1]/.5)},${Math.floor((wrap(t[2])+Math.PI)/.2)}`);needed=adaptive?kldRequired(bins.size,eps):800;}out.forEach(p=>p.w=1/out.length);this.particles=out;this.bins=bins.size;this.stage='KLD resampling';}
 estimate(){let x=0,y=0,c=0,s=0;for(const p of this.particles){x+=p.t[0]*p.w;y+=p.t[1]*p.w;c+=Math.cos(p.t[2])*p.w;s+=Math.sin(p.t[2])*p.w;}return[x,y,Math.atan2(s,c)];}
}
const api={wrap,rng,normal,walls,transform,inverse,mapPoints,ray,scan,nearest,fitRigid,icp,grid,ndtCost,ndt,wallDistance,likelihood,kldRequired,ParticleFilter};if(typeof module!=='undefined')module.exports=api;root.Localization=api;
})(typeof window!=='undefined'?window:globalThis);
