'use strict';
const D=window.MappingData,$=id=>document.getElementById(id),S=$('sensor'),M=$('map'),ctx=S.getContext('2d'),mc=M.getContext('2d');
const state={mode:location.hash==='#lidar'?'lidar':'visual',index:10,playing:false,selected:null,yaw:0,zoom:1,pan:[0,0]};window.MappingLab={state,data:D,render};
const C={used:'#48f4a2',unused:'#f5a343',plane:'#46d7ff',old:'#738ca8',new:'#48f4a2',path:'#ffc35a',selected:'#e690ff'};let clock=null,renderToken=0;const images=new Map();
function image(i){if(!images.has(i)){const im=new Image();im.src=D.frames[i].image;images.set(i,new Promise(resolve=>{im.onload=()=>resolve(im);im.onerror=()=>resolve(null)}));}return images.get(i)}
function line(c,a,b,color,width=1){c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(...a);c.lineTo(...b);c.stroke()}
function point(c,p,color,r=2){c.fillStyle=color;c.beginPath();c.arc(p[0],p[1],r,0,Math.PI*2);c.fill()}
function label(c,t,x,y,size=23,color='#cfdeed'){c.fillStyle=color;c.font=`${size}px Arial`;c.fillText(t,x,y)}
function project3(p,center,scale,w,h,oblique=false){let x=p[0]-center[0],y=p[1]-center[1],z=(p[2]||0)-(center[2]||0);const a=state.yaw,u=Math.cos(a)*x-Math.sin(a)*y,v=Math.sin(a)*x+Math.cos(a)*y;return [w/2+u*scale*state.zoom+state.pan[0],h/2-(oblique?v*.55+z*.85:v)*scale*state.zoom+state.pan[1]]}
function vpoint(p){return [p[0],p[2],-p[1]]} // camera x-right, y-down, z-forward
function transform(p,T){return T.slice(0,3).map(row=>row[0]*p[0]+row[1]*p[1]+row[2]*p[2]+row[3])}
function grid(c,proj,range,step){for(let v=-range;v<=range;v+=step){line(c,proj([v,-range,0]),proj([v,range,0]),'#1b344c');line(c,proj([-range,v,0]),proj([range,v,0]),'#1b344c')}}
async function sensorVisual(f,token){const [prev,im]=await Promise.all([image(Math.max(0,state.index-1)),image(state.index)]);if(token!==renderToken)return;ctx.clearRect(0,0,S.width,S.height);if(!im){label(ctx,'Frame unavailable',40,80);return}ctx.drawImage(prev,0,38,1242,375);ctx.drawImage(im,0,455,1242,375);label(ctx,'PREVIOUS FRAME',16,27,23);label(ctx,'CURRENT FRAME',16,443,23);if(!$('overlays').checked)return;
for(const t of f.visual.tracks){if(!t.used&&!$('rejected').checked)continue;const col=t.id===state.selected?C.selected:t.used?C.used:C.unused;const r=t.id===state.selected?8:3;point(ctx,[t.a[0],t.a[1]+38],col,r);point(ctx,[t.b[0],t.b[1]+455],col,r);if($('matches').checked){line(ctx,[t.b[0]-(t.b[0]-t.a[0])*3,t.b[1]+455-(t.b[1]-t.a[1])*3],[t.b[0],t.b[1]+455],col,1.5);if(t.id===state.selected)line(ctx,[t.a[0],t.a[1]+38],[t.b[0],t.b[1]+455],col,2)}if(t.id===state.selected)label(ctx,'Track '+t.id,t.b[0]+12,t.b[1]+446,22,C.selected)} }
function sensorLidar(f){ctx.clearRect(0,0,S.width,S.height);const l=f.lidar,used=new Set(l.usedIndices);const proj=p=>[621-p[1]*14,600-p[0]*14];grid(ctx,p=>[621-p[1]*14,600-p[0]*14],40,5);label(ctx,'CURRENT SCAN · SENSOR COORDINATES · METERS',20,35);label(ctx,'Front',600,80,20);const invR=l.pose.slice(0,3).map(r=>r.slice(0,3)),t=l.pose.slice(0,3).map(r=>r[3]);const inverse=q=>[0,1,2].map(j=>invR.reduce((s,r,k)=>s+r[j]*(q[k]-t[k]),0));
for(let j=0;j<l.scan.length;j++){if(!$('rejected').checked&&!used.has(j))continue;point(ctx,proj(l.scan[j]),$('overlays').checked&&used.has(j)?C.plane:'#8298ad',used.has(j)?3:1.5)}if($('overlays').checked&&$('matches').checked)for(const p of l.pairs){line(ctx,proj(l.scan[p.source]),proj(inverse(p.q)),C.unused,2);point(ctx,proj(inverse(p.q)),C.used,2)}point(ctx,proj([0,0,0]),C.path,8);label(ctx,'5 m grid · cyan samples participate in planar registration',20,808,21);}
function map(f){mc.clearRect(0,0,M.width,M.height);const visual=state.mode==='visual',all=visual?D.visualMap:D.lidarMap;const path=D.frames.slice(0,state.index+1).filter((f,i)=>!visual||i>=5).map(f=>visual?vpoint(f.visual.pose):f.lidar.pose.slice(0,3).map(r=>r[3]));const current=path.at(-1)||[0,0,0];const center=visual?[0,9,0]:[45,0,0],scale=visual?19:5.8,proj=p=>project3(p,center,scale,M.width,M.height,$('view').value==='oblique');grid(mc,proj,visual?35:70,visual?5:10);const items=all.filter(p=>p.at<=state.index&&($('accumulate').checked||p.at===state.index));
for(const item of items){const p=visual?vpoint(item.p):item.p,col=item.id===state.selected&&visual?C.selected:item.at===state.index?C.new:C.old;point(mc,proj(p),col,item.id===state.selected&&visual?7:visual?2.8:1)}
for(let j=1;j<path.length;j++)line(mc,proj(path[j-1]),proj(path[j]),C.path,3);point(mc,proj(current),C.new,7);label(mc,visual?'SPARSE LANDMARK MAP · ARBITRARY UNITS':'SURFACE MAP · METERS',20,30,22);label(mc,`Visible map points: ${items.length}`,20,690,20);if(visual&&state.index<5)label(mc,'Collecting parallax for initialization',150,300,28);if(state.selected!==null&&visual){const p=D.visualMap.find(p=>p.id===state.selected&&p.at<=state.index);if(p){line(mc,proj(current),proj(vpoint(p.p)),C.selected,2);label(mc,'Landmark '+p.id,...proj(vpoint(p.p)),20,C.selected)}}window.MappingLab.visibleMapCount=items.length;}
function metric(v,name){return `<div class="metric"><strong>${v}</strong><span>${name}</span></div>`}
function selection(f,visual){$('select-inlier').hidden=!visual;$('clear-selection').hidden=!visual;if(!visual){$('selection').textContent='Cyan samples constrain scan alignment; orange lines connect them to local map correspondences.';return}const t=f.visual.tracks.find(t=>t.id===state.selected);$('selection').textContent=state.selected===null?'Click a feature in the current image to follow its map landmark.':t?`Track ${t.id}: ${t.used?'pose inlier':'unused for this pose'}. ${t.mapped?'Its triangulated landmark is highlighted in the map.':'This observation has no accepted 3D landmark.'}`:`Track ${state.selected} is not observed in this frame. Its accepted map landmark remains highlighted.`;}
async function render(){const token=++renderToken,f=D.frames[state.index],v=state.mode==='visual';$('frame').value=state.index;$('time').textContent=`${f.frame} · ${f.time.toFixed(1)} s`;
selection(f,v);
$('select-inlier').disabled=!v;$('clear-selection').disabled=!v;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===state.mode)));$('sensor-title').textContent=v?'Previous and current image tracks':'LiDAR surface samples and matches';$('legend').innerHTML=v?'<span class="dot used">Pose inlier</span><span class="dot unused">Tracked but unused</span><span class="dot selected">Selected landmark</span>':'<span class="dot plane">Used surface samples</span><span class="dot new">Matched map point</span><span class="dot unused">Residual lines</span>';
if(v){$('metrics').innerHTML=metric(f.visual.tracks.length,'Forward/backward consistent tracks')+metric(f.visual.used,'Pose inliers')+metric(f.visual.mapped,'Mapped landmarks')+metric(f.visual.rmse===null?'—':f.visual.rmse+' px','Inlier reprojection RMSE');$('explanation').textContent=f.visual.status+'. Green tracks constrain the camera pose. Triangulated features enter the sparse map only after depth, parallax, and reprojection checks. Orange tracks may lack depth or fail the pose test.';$('map-caption').textContent='Top down: horizontal axis is camera-right, vertical axis is forward. One initial baseline = one arbitrary unit. Drag to rotate the map, use the mouse wheel to zoom.';$('algorithm').textContent=D.meta.estimators.split(' LiDAR:')[0];await sensorVisual(f,token);}
else{$('metrics').innerHTML=metric(f.lidar.scan.length,'Voxel scan samples')+metric(f.lidar.accepted,'Accepted planar correspondences')+metric(f.lidar.trace.length,'ICP updates')+metric(f.lidar.rmse===null?'—':f.lidar.rmse+' m','Point-to-plane RMSE');$('explanation').textContent='The estimator aligns this scan with the preceding local map. Cyan points mark the surface samples used in the registration objective. Match lines show a subset for readability. Orange segments connect each sample to its matched map point. After alignment, transformed returns extend the map.';$('map-caption').textContent='Top down: LiDAR x-forward and y-left in the first scan’s coordinate frame. 10 m grid. Drag to rotate the map, use the mouse wheel to zoom. No per-point motion correction is applied.';$('algorithm').textContent='LiDAR: '+D.meta.estimators.split(' LiDAR:')[1];sensorLidar(f);}if(token===renderToken)map(f);}
function pause(){state.playing=false;clearInterval(clock);$('play').textContent='Play'}
function play(){pause();if(state.index===D.frames.length-1)state.index=0;state.playing=true;$('play').textContent='Pause';clock=setInterval(()=>{if(state.index===D.frames.length-1){pause();return}state.index++;render()},100/Number($('speed').value))}
$('play').onclick=()=>state.playing?pause():play();$('speed').onchange=()=>{if(state.playing)play()};$('next').onclick=()=>{pause();state.index=Math.min(D.frames.length-1,state.index+1);render()};$('previous').onclick=()=>{pause();state.index=Math.max(0,state.index-1);render()};$('reset').onclick=()=>{pause();state.index=0;state.selected=null;render()};$('frame').max=D.frames.length-1;$('frame').oninput=()=>{pause();state.index=Number($('frame').value);render()};for(const id of ['overlays','rejected','matches','accumulate','view'])$(id).onchange=render;
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{pause();state.mode=b.dataset.mode;state.selected=null;state.yaw=0;state.zoom=1;state.pan=[0,0];location.hash=state.mode;render()});$('camera-reset').onclick=()=>{state.yaw=0;state.zoom=1;state.pan=[0,0];render()};
S.onclick=e=>{if(state.mode!=='visual')return;const r=S.getBoundingClientRect(),p=[(e.clientX-r.left)/r.width*S.width,(e.clientY-r.top)/r.height*S.height-455];const tracks=D.frames[state.index].visual.tracks;let best=null,d=22;for(const t of tracks){const n=Math.hypot(p[0]-t.b[0],p[1]-t.b[1]);if(n<d){d=n;best=t}}state.selected=best?.id??null;$('selection').textContent=best?`Track ${best.id}: ${best.used?'pose inlier':'unused for this pose'}. ${best.mapped?'Its triangulated landmark is highlighted in the map.':'This observation has no accepted 3D landmark.'}`:'Click a feature in the current image to follow its map landmark.';render()};let drag=null;M.onpointerdown=e=>{drag=[e.clientX,state.yaw];M.setPointerCapture(e.pointerId)};M.onpointermove=e=>{if(drag){state.yaw=drag[1]+(e.clientX-drag[0])*.008;map(D.frames[state.index])}};M.onpointerup=()=>drag=null;M.onwheel=e=>{e.preventDefault();state.zoom=Math.min(5,Math.max(.3,state.zoom*Math.exp(-e.deltaY*.001)));map(D.frames[state.index])};
$('provenance').textContent=`${D.meta.dataset}, sequence ${D.meta.sequence}, original frames ${D.meta.start}–${D.meta.start+D.meta.count-1}. ${D.meta.dt_note}`;$('selection').textContent='Click a feature in the current image to follow its map landmark.';render();

if(location.protocol==='file:'){document.querySelector('.downloads').innerHTML='<a href="../../Presentations/Lecture%206%20Mapping%20for%20Autonomous%20Driving.pptx">Open local lecture slides</a>'; }

$('select-inlier').onclick=()=>{const tr=D.frames[state.index].visual.tracks.find(t=>t.used&&t.mapped);state.selected=tr?.id??null;$('selection').textContent=tr?'Track '+tr.id+': pose inlier. Its triangulated landmark is highlighted in the map.':'No mapped pose inlier at this frame.';render()};$('clear-selection').onclick=()=>{state.selected=null;$('selection').textContent='Click a feature in the current image to follow its map landmark.';render()};
