"""Course content, sources, and instructor notes for Lecture 6."""
from pathlib import Path
import json
H=Path(__file__).resolve().parent
V='https://arxiv.org/abs/2007.11898'
V2='https://arxiv.org/abs/1610.06475'
L='https://www.roboticsproceedings.org/rss10/p07.html'
O='https://octomap.github.io/'
CV='https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html'
TR='https://docs.opencv.org/4.x/dc/d6b/group__video__track.html'
F='https://docs.opencv.org/4.x/d4/d8c/tutorial_py_shi_tomasi.html'
K='https://www.cvlibs.net/datasets/kitti/'
G='https://borglab.github.io/gtsam/gpsfactor/'
GPS='https://www.gps.gov/gps-accuracy'
I='https://arxiv.org/abs/2007.00258'
C=[]
def add(title,body,notes,refs,layout='text',media=None,demo=None,equations=None,table=None):
 C.append(dict(slide=len(C)+1,title=title,body=body,notes=notes,refs=refs,layout=layout,media=[media] if media else [],demo=demo,equations=equations or [],table=table,take=''))
add('Mapping for autonomous driving',['Mapping','Visual SLAM and LiDAR mapping','Introduction to Autonomous Driving · Fall 2026'], 'Suggested pacing: 100–110 minutes, including 25 minutes of frame-by-frame exploration. Begin with the known-map localization problem from Lecture 5. Here the vehicle also has to build the map it uses.',[V,L])
add('Learning goals',['Explain how successive observations constrain motion and map structure.','Follow visual landmarks and LiDAR surface correspondences.','Compare sensor tradeoffs and diagnose GPS, terrain, and loop-closure effects.'], 'Students should explain each intermediate result, rather than only recognize algorithm names. Ask them to trace one accepted observation through detection, association, pose estimation, and map insertion.',[V,L])
add('Localization, mapping, and SLAM',['Localization estimates a pose in an existing map.','Mapping combines observations using their sensor poses.','SLAM estimates the trajectory and map together.'], 'In Lecture 5, ICP and NDT matched observations to a known map. For SLAM the target map grows and may also need correction. A wrong pose places otherwise correct measurements in the wrong location.',[V,L])
add('Map representations',[], 'A visual feature map supports pose estimation but its sparse points do not imply that unobserved space is free. Point clouds record sampled surfaces. Occupancy maps explicitly distinguish free, occupied, and unknown areas. Semantic maps add meaning, while metric geometry still needs consistent poses.',[V2,O],layout='table',table=[['Representation','Stored information','Typical use'],['Sparse landmarks','3D points and observations','Visual localization'],['Point cloud / surfels','Surface geometry','Registration and reconstruction'],['Occupancy grid / voxels','Free, occupied, unknown','Planning and exploration'],['Semantic map','Geometry with labels','Task and scene reasoning']])
add('The pose places each observation',['T maps sensor coordinates into the chosen map frame.','A pose error shifts or rotates every point in the new frame.'], 'Define p_s as a sensor-frame measurement and p_m as a map-frame point. Calibration connects camera, LiDAR, and vehicle frames. A SLAM map normally chooses its first pose as the local origin. It does not automatically supply global latitude and longitude.',[L,CV],layout='equation',equations=['p_map = R p_sensor + t','T = [ R  t ; 0  1 ]'])
add('The SLAM pipeline',['Associate the current observations with earlier observations or map elements.','Estimate pose, then add useful new map structure.','Refine local estimates and verify revisited places.'], 'Separate the front end, which makes associations and estimates motion, from the back end, which revises poses and map structure using accumulated constraints. Sensor-specific residuals differ, but both approaches need reliable associations.',[V,L],layout='steps')
add('The real driving sequence',['KITTI tracking sequence 0001.','80 camera and LiDAR frames at nominal 10 Hz.','Both maps use estimated poses.'], 'Open the demo. It uses original frames 20 through 99, with time relative to the chosen excerpt. The visual map starts after a two-view initialization. The LiDAR map starts at the first scan. These are local mapping traces, not an ORB-SLAM3 or LOAM run.',[K],layout='visual',media='sequence.png',demo='visual')
add('Visual features',['Corners vary in more than one image direction.','A track links the same image detail across time.','Depth and geometry decide whether it becomes a landmark.'], 'A uniform road patch gives little information about local translation. A long straight edge constrains displacement mainly across that edge. Corners provide stronger 2D localization. The demo uses Shi-Tomasi corners; ORB systems use their own detection and descriptor machinery.',[F],layout='visual',media='features.png')
add('Tracking across video frames',['Green tracks contribute to pose estimation.','Orange tracks remain unused for the current pose.','Track identity connects an observation to a 3D landmark.'], 'Play the real frames at quarter speed. The demo runs pyramidal Lucas-Kanade offline, then checks tracking forward and backward. Optical flow supplies candidate correspondences. It does not itself reconstruct the map or establish whether every feature belongs to a static object.',[TR,CV],layout='visual',media='visual-tracking.gif',demo='visual')
add('Robust correspondence checks',['Tracking consistency removes unreliable image matches.','RANSAC finds a pose supported by many mapped observations.','Reprojection error tests the agreement with that pose.'], 'At original frame 50, many features are tracked, but only a subset has valid map depth and passes PnP RANSAC. Rejected observations may come from ambiguity, inaccurate depth, noise, or motion. Do not present the orange overlay as a semantic moving-object mask.',[CV,TR],layout='visual',media='inliers.png',demo='visual')
add('The camera projection model',['A 3D landmark predicts a pixel at a candidate camera pose.','Depth disappears in projection, so one pixel defines a viewing ray.'], 'Use X_c = R_cw X_w + t_cw, where the transform maps world to camera. K contains calibrated focal length and principal point. A monocular observation alone does not reveal how far along the ray the landmark lies.',[CV],layout='equation',equations=['X_camera = R_camera,world X_world + t','u = f_x X / Z + c_x','v = f_y Y / Z + c_y'])
add('Parallax and triangulation',['Two views of a static point provide two viewing rays.','Camera translation creates parallax between the observations.','Small parallax makes depth sensitive to pixel error.'], 'Explain triangulation as finding the 3D point consistent with observations from different camera centers. Pure rotation changes image coordinates but does not provide a translation baseline for new depth. Distant features can track well while giving weak depth constraints. The demo applies positive-depth, parallax, and reprojection tests.',[CV,V2],layout='visual',media='triangulation.png')
add('Monocular initialization',['Estimate relative rotation and translation direction from image matches.','Choose an initial baseline as one map unit.','Triangulate a first set of sparse landmarks.'], 'The essential matrix constrains matching normalized image coordinates. Decomposing it yields relative R and the direction of t. The magnitude of t remains unknown in ordinary monocular geometry. The demo initializes using five frames of parallax, with no LiDAR or reference-pose input.',[CV],layout='equation',equations=['x₂ᵀ E x₁ = 0','E = [t]× R','Initial baseline length = 1 arbitrary unit'])
add('Pose estimation against a visual map',['Mapped 3D landmarks supply correspondences to current pixels.','PnP estimates the camera pose.','Only geometrically consistent inliers constrain the update.'], 'PnP uses 3D-to-2D correspondences. In this demo solvePnPRansac estimates the pose, followed by nonlinear refinement on its inliers. Define the residual as observed pixel minus projected pixel. A small residual on accepted inliers does not guarantee a globally accurate map.',[CV],layout='equation',equations=['r_ij = u_ij − π(K, T_camera,world X_j)','Pose update minimizes Σ ρ(‖r_ij‖²)'])
add('Keyframes and new map points',['Keyframes preserve useful views of the scene.','New observations need sufficient baseline before triangulation.','Repeated observations allow a landmark to support later poses.'], 'A full system selects informative keyframes and removes weak or redundant points. The teaching mapper uses regular anchor frames to keep the mechanism inspectable. Click a green inlier in the demo to show the associated landmark and its line to the estimated camera position.',[V,V2],layout='visual',media='landmark.png',demo='visual')
add('Bundle adjustment',['Optimize camera poses and landmark positions together.','Use repeated observations to reduce reprojection error.','Fix the coordinate gauge so the solution is well defined.'], 'Contrast PnP, which solves a pose against currently fixed map points, with bundle adjustment, which also adjusts landmark coordinates and other poses. Robust losses reduce the effect of remaining bad associations. Monocular BA needs a fixed origin and scale convention. The short demo does not perform BA.',[V,CV],layout='equation',equations=['min over {T_i, X_j}  Σ_(i,j) ρ(‖u_ij − π(K,T_i X_j)‖²)','Unknowns: camera poses and 3D landmarks'])
add('Drift and loop closure',['Small local estimation errors accumulate over a trajectory.','Place recognition proposes an earlier location.','Geometric verification supplies a loop constraint for correction.'], 'A similar-looking building is only a candidate. Verify the relative geometry before adding the loop edge. Graph optimization or BA distributes correction across poses and map points. A short forward-driving clip without a revisit cannot demonstrate a genuine loop closure, so the recorded replay has no loop. The separate controlled scenario supplies an explicitly verified return constraint at lap end; it does not perform place recognition.',[V,V2])
add('Scale in visual mapping',[], 'Stereo uses a calibrated physical baseline. RGB-D gives measured depth within its range. Visual-inertial systems can recover metric scale when calibration and excitation support it. The demo intentionally uses monocular frames and arbitrary scale, which is preserved during later PnP updates.',[V,V2,CV],layout='table',table=[['Sensor configuration','Depth / scale cue','Main limitation'],['Monocular camera','Motion and parallax','Unknown metric scale'],['Stereo cameras','Known camera baseline','Depth weak at long range'],['RGB-D camera','Measured depth','Range and sensing conditions'],['Camera + IMU','Inertial constraints','Calibration and initialization']])
add('Visual SLAM advantages',['Cameras capture rich appearance with compact hardware.','Distinctive texture supports landmarks and place recognition.','Image data can also support semantic interpretation.'], 'Do not claim that a sparse feature SLAM map already contains semantic labels. Appearance can help recognize places, while another perception stage may attach object or road semantics. Cost, power, and compute depend on the particular camera and algorithm.',[V,V2])
add('Visual SLAM limitations',['Low texture, blur, and changing illumination weaken matching.','Repeated patterns create ambiguous correspondences.','Monocular depth and scale require additional constraints.'], 'Compare a textured facade with a blank wall, and a clear exposure with motion blur. Moving objects can dominate observations if the static scene is poorly visible. Relocalization, additional cameras, depth sensors, or an IMU can improve robustness, but cannot remove all sensing failures.',[V,V2])
add('Visual methods beyond feature tracking',['Direct methods minimize photometric error at selected pixels.','Dense methods estimate more of the visible surface.','The map representation depends on the estimator and sensors.'], 'Keep the scope clear: visual SLAM is a family, not a synonym for corner tracking. The lecture and demo focus on feature-based sparse mapping because correspondences are visible. Direct methods use image intensity consistency and require attention to exposure, calibration, and scene assumptions.',[V])
add('LiDAR observations',['Each return measures range and direction to a sampled surface.','A scan contains points collected over a period of time.','Registration estimates the transform that aligns overlapping geometry.'], 'Switch the demo to LiDAR at the same original frame. The displayed view is a projection of real 3D returns. LiDAR provides metric depth, but still requires correct pose estimation to put the returns into a consistent map.',[L],layout='visual',media='lidar-scan.png',demo='lidar')
add('LiDAR preprocessing',['Remove invalid returns and select a useful range.','Voxel sampling reduces repeated nearby points.','Deskew compensates for sensor motion during a scan.'], 'The demo filters invalid and extreme ranges, uses voxel samples, and limits the display density. It lacks per-point timestamps and does not deskew. Explain that the lack of deskew can bend apparent surfaces and bias registration during motion. An IMU or motion estimate may supply a trajectory for deskew.',[L])
add('Geometry used for registration',['Planes constrain motion along their surface normals.','Edges provide other geometric constraints.','The scene must contain enough independent structure.'], 'LOAM uses edge and planar feature points with different residuals. The demo uses a simpler PCA planarity test and point-to-plane ICP. It does not implement LOAM edge selection. A single flat surface poorly constrains sliding within the surface and rotation around its normal.',[L],layout='visual',media='lidar-planes.png',demo='lidar')
add('Scan registration objectives',['Point-to-point uses distance between corresponding samples.','Point-to-plane uses displacement along the map surface normal.','NDT compares points with local map distributions.'], 'Connect this slide to Lecture 5. Point-to-plane and NDT make use of local geometry, but both need overlap and a reasonable initial estimate. The choice of objective changes which errors are penalized and how local structure affects the solution.',[L,'https://pointclouds.org/documentation/tutorials/normal_distributions_transform.html'],layout='equation',equations=['Point-to-point: r = R p + t − q','Point-to-plane: r = nᵀ(R p + t − q)'])
add('Scan-to-map registration',['Predict the next pose from recent motion.','Match current surface samples to the local map.','Refine the pose with a robust geometric objective.'], 'The local map contains the preceding eight registered scans. Neighbor covariance supplies PCA normals and a planarity score. Distance and planarity checks gate correspondences. A robust loss downweights large normal residuals. The display shows a subset of accepted correspondences so the geometry stays readable.',[L],layout='visual',media='lidar-registration.gif',demo='lidar')
add('Map integration',['Transform the accepted scan into the map frame.','Accumulate surface observations using the estimated pose.','Manage map resolution and remove inconsistent structure.'], 'The demo inserts decimated returns after registration. Distinguish the points used to estimate a pose from the larger set that may be inserted afterward. A production persistent map needs better outlier and dynamic-object handling. Every point remains revisable when its supporting pose changes.',[L],layout='visual',media='lidar-growth.gif',demo='lidar')
add('Occupancy and free space',['A return supplies evidence for an occupied endpoint.','The ray supplies evidence for free space before the return.','Space outside observed rays remains unknown.'], 'A point cloud does not automatically encode safe free space. Occupancy mapping uses a sensor model and repeated observations to update probabilities. OctoMap stores probabilistic occupancy in an octree. Show why an empty-looking area with no measurements cannot be treated as free.',[O])
add('LiDAR mapping advantages',['Measured range provides metric scene geometry.','Ambient lighting and image texture matter less.','Surface maps support geometric localization and reconstruction.'], 'A dark but geometrically structured street can remain useful to active ranging. LiDAR maps can support scan matching and reconstruction. Map density depends on the sensor, distance, viewpoint, and accumulation, so avoid promising uniformly dense coverage.',[L])
add('LiDAR mapping limitations',['Sparse or repetitive geometry weakens observability.','Motion distortion and moving objects corrupt alignment.','Weather, glass, and weak returns can reduce useful measurements.'], 'A corridor can constrain lateral position while leaving motion along it uncertain. Flat ground alone leaves several directions weakly constrained. Fog, rain, reflective surfaces, and material response can affect returns. Sensor price, size, power, and compute are system-specific tradeoffs.',[L,'https://arxiv.org/abs/1912.03251'])
add('Visual and LiDAR mapping',[], 'Use this table to compare evidence rather than nominate an unconditional winner. Both sensors need calibration, overlap, and static-environment support. A camera can supply rich appearance while a LiDAR supplies geometry. Their common failure modes include bad association and accumulated pose error.',[V,L],layout='table',table=[['Dimension','Visual mapping','LiDAR mapping'],['Primary evidence','Appearance across images','Range and surface geometry'],['Typical map','Sparse landmarks / depth','Surface points / voxels'],['Scale','Depends on sensor configuration','Metric ranging'],['Weak scene','Dark, blurred, low texture','Sparse or repetitive geometry'],['Practical tradeoff','Compact sensors, rich appearance','Direct depth, sensor resources']])
add('Mapping in different environments',[], 'Treat these as scenario-based reasoning, not benchmark rankings. In an indoor corridor, camera texture and 3D structural variety both matter. At night, LiDAR may retain useful geometry while visual matching degrades. Moving traffic affects both modalities. More sensor types help when they provide independent constraints.',[V,L],layout='table',table=[['Environment','Visual concern','LiDAR concern'],['Textured indoor space','Blur and exposure','Glass and limited overlap'],['Long corridor','Repeated appearance','Weak motion along corridor'],['Night driving','Low light and glare','Return strength and geometry'],['Open highway','Distant features, weak parallax','Few stable nearby structures'],['Busy street','Many moving image features','Moving surfaces and ghost points']])
add('Dynamic objects and map quality',['A static-scene model cannot explain independent object motion.','Robust estimation rejects some inconsistent observations.','Persistent mapping needs checks across time and viewpoints.'], 'Parked and moving vehicles can look similar in one image or scan. Geometry-only rejection is not a semantic motion classifier. Temporal persistence and explicit dynamic-object handling improve static maps. Transient obstacles still belong in perception and planning, even when excluded from the persistent map.',[V,L])
add('Camera, LiDAR, and IMU fusion',['IMU measurements help predict rapid motion and support deskew.','Camera appearance and LiDAR geometry supply different constraints.','Timing and extrinsic calibration connect all measurements.'], 'Connect to Lecture 4. Fusion needs consistent clocks and transforms, as well as a model of uncertainty. A miscalibrated extrinsic transform can make two accurate sensors disagree. Fusion also adds computational and calibration work, and it does not guarantee observability in every environment.',[V,L])
add('GPS anchors a local map',['Convert GPS into the map frame before adding a position factor.','Weight each fix using its measurement covariance.'], 'GNSS supplies external position constraints. A GPS factor predicts the antenna position from the vehicle pose plus the calibrated antenna lever arm. Convert geodetic coordinates into a consistent local Cartesian frame such as ENU and establish map alignment. The controlled demo assumes this alignment is known and the lever arm is zero. It solves a simplified position chain; GPS does not directly observe heading there. A monocular system needs appropriate scale/frame alignment before using metric factors. A single antenna position factor does not directly observe all orientation components.',[G,I],layout='equation',equations=['r_GPS = p + R ℓ_antenna − g','GPS cost = r_GPSᵀ Σ_GPS⁻¹ r_GPS'])
add('GPS helps when its uncertainty is credible',[], 'Satellite geometry, obstruction, multipath, receiver quality and correction services affect accuracy. A small reported covariance can be misleading when an unmodeled bias is present. Do not promise centimeter accuracy for generic GPS. The demo sigma controls both generated noise and factor weight, so it represents an honestly modeled receiver. The biased-GPS option deliberately violates that assumption. Innovation gating is useful but can also reject good measurements when the prediction or uncertainty model is poor.',[GPS,G,I],layout='table',table=[['Condition','Effect on mapping','Response'],['Reliable position fixes','Bound accumulated position drift','Fuse with credible covariance'],['Noisy fixes','Weaker absolute constraints','Lower factor weight'],['Blocked satellites / outage','Local drift grows between fixes','Continue local estimation'],['Multipath / position bias','Wrong anchors can deform map','Gate; robustify; check consistency'],['Wrong timing / lever arm','Systematic pose disagreement','Calibrate and synchronize']])
add('Experiment: GPS off versus on',['Left: drifting odometry, GPS off.','Right: the same motion with GPS factors.'], 'Controlled synthetic loop, default settings: hill 6 percent, bump 0.18 m, odometry drift 1x, GPS horizontal sigma 0.6 m, 3D model, no loop closure. Position RMS is about 2.10 m without GPS and 0.56 m with GPS. Map RMS changes from about 2.13 m to 0.80 m. These deterministic examples are not KITTI scores or general performance claims. White is reference, orange is odometry, cyan is the estimated path, purple is GPS. Ask why the GPS-corrected return can still have a gap and why orientation errors remain.',[G,GPS,I],layout='pair')
C[-1]['media']=['challenge-no-gps.png','challenge-gps.png'];C[-1]['labels']=['GPS off · position RMS 2.10 m','GPS on · position RMS 0.56 m']
add('Slopes require a pose with height and tilt',['3D poses include x, y, z and roll, pitch, yaw.','A planar approximation can misplace observations on uneven roads.'], 'A planar pose can be appropriate for a deliberately flat-world task, but a metric 3D surface map needs the orientation and elevation of its sensor. On a slope, pitching the sensor changes both the height and horizontal position of transformed observations. For a small angular error delta theta, a point at range d can move by roughly d times delta theta. At 20 m, a 1 degree error is about 0.35 m. The demo varies pitch and elevation; roll remains zero. This is an illustration of model mismatch, not a full six-degree-of-freedom estimator.',[L,I],layout='equation',equations=['p_map = R(roll, pitch, yaw) p_sensor + [x, y, z]ᵀ','Point displacement ≈ range × angular error','20 m × (1° × π / 180) ≈ 0.35 m'])
add('Bumps change motion within a frame or scan',['Rapid pitch and vertical motion can break a constant-pose assumption.','Camera blur and rolling shutter can weaken visual tracking.','A rotating LiDAR needs motion compensation during its scan.'], 'A bump does not inherently make SLAM fail. Problems arise if motion is poorly observed, the model ignores tilt, or measurements from different times are treated as one rigid observation. An IMU can predict rapid rotation and help deskew LiDAR points, provided timing and calibration are correct. Camera exposure and rolling shutter require their own models. LIO-SAM uses inertial preintegration for point-cloud deskew and initial guesses. The controlled demo shows frame-to-frame height/pitch effects only; it does not synthesize rolling scans, motion blur, rolling shutter or IMU estimation.',[I,L,V])
add('Experiment: planar versus 3D terrain',['Left: height and pitch excluded.','Right: elevation and pitch retained.'], 'Controlled comparison: hill 12 percent, bump 0.50 m, zero odometry noise/drift, GPS off, no loop closure. Planar map RMS is about 2.63 m; with the correct 3D model it is approximately zero. This isolates model mismatch from noise. The reference road is white; green map points are below 0.25 m error, yellow 0.25–0.8 m, red above 0.8 m. Returning near the start does not establish map correctness: the planar model nearly closes the path while still deforming the road.',[L,I],layout='pair')
C[-1]['media']=['challenge-planar.png','challenge-3d.png'];C[-1]['labels']=['Planar model · map RMS 2.63 m','3D model · noise-free geometry']
add('When mapping goes wrong',[], 'Pose estimation and integration are separate decisions. A low residual on a degenerate plane or repeated appearance is not enough to establish reliable motion. A false match can create a sudden jump, and integrating measurements under the wrong pose creates ghost walls, duplicated surfaces or a bent road. Tracking loss should change confidence and insertion policy. Downstream localization can inherit map errors; planning that relies on incorrect geometry or free-space inference can make unsafe decisions. Preserve a recovery path through relocalization, local submaps or other sensors rather than accumulating unsupported geometry.',[V,L,I],layout='table',table=[['Failure','Visible consequence','Useful response'],['False association','Pose jump; duplicated surfaces','Geometric / motion checks'],['Tracking lost','Uncertain predicted motion','Pause insertion; relocalize'],['Weak geometry / texture','Drift in unconstrained directions','Check observability; add evidence'],['Biased GPS','Trajectory pulled off the road','Innovation / covariance checks'],['Wrong sensor pose model','Bent or displaced road surfaces','Model 3D motion; calibrate']])
add('Mapping errors affect the driving stack',['Incorrect map geometry biases later localization.','Duplicated surfaces or false free space can mislead planning.','Monitor confidence, pause unsupported insertion, and recover.'], 'A map is evidence accumulated from measurements and estimated poses. If the poses are wrong, measurements may be individually accurate but collectively inconsistent. Localization against such a map can be biased or fail; planning may inherit incorrect obstacle or traversability geometry. Keep unknown space distinct from free space. A persistent mapper should support relocalization, corrected submaps, reintegration and removal of transient objects. The demo visualizes geometric errors; it does not simulate vehicle planning or a safety fallback.',[V,L,O])
add('Experiment: reject a false match',['Left: a bad pose enters the map.','Right: the motion gate skips that insertion.'], 'A controlled false translation/yaw match is injected at frame 50. This screenshot uses hill 12 percent, bump 0.50 m, no drift, no GPS and no loop. Map RMS is about 6.29 m with the gate off and 0.08 m with it on. The gate substitutes a weaker motion prediction and skips one scan. It does not guarantee perfect recovery. Try tracking loss separately: frames 50–67 have only predicted motion, and the insertion gate skips 18 scans. Bad mapping can persist even after tracking resumes. The synthetic quality flag represents a detector decision, not a validated production failure detector.',[V,L,I],layout='pair')
C[-1]['media']=['challenge-bad-match.png','challenge-gated-match.png'];C[-1]['labels']=['Gate off · map RMS 6.29 m','Gate on · map RMS 0.08 m']
add('What if there is no loop closure?',['Local mapping continues while uncorrected drift accumulates.','A revisited street may appear twice or fail to line up.','GPS bounds position drift but does not replace every loop constraint.'], 'Loop closure is possible only when the vehicle revisits a recognizable place and verifies a consistent relative pose. No revisit, failed recognition, or failed geometric verification means no loop edge. Missing loop closure does not make every map unusable, and a loop is not required to finish every short drive. GPS anchors can improve global position while relative geometry and heading still drift. A falsely accepted loop can be worse than a missed loop. In the controlled demo the loop edge remains unavailable until frame 120 even when the switch is enabled.',[V,V2,I,G])
add('Close the loop and correct the map',['Left: GPS helps, with no return constraint.','Right: corrected poses rebuild the map geometry.'], 'Controlled default settings, same GPS factors in both images. Map RMS is about 0.80 m without the loop and 0.36 m with it; return separation changes from 1.38 m to about 0.003 m. The heading chain receives a 2 pi return rotation and the position graph receives a start/end displacement constraint. This simplified split graph is not full nonlinear SE(3) optimization or automatic loop detection. Disable Rebuild map after correction: the corrected path remains, but old map geometry retains about 2.13 m RMS because scans still use the odometry poses. In real systems revise landmarks, rebuild submaps or reintegrate measurements using corrected poses.',[V,I,G],layout='pair')
C[-1]['media']=['challenge-loop-before.png','challenge-loop.png'];C[-1]['labels']=['GPS only · return gap 1.38 m','GPS + verified loop · rebuilt map']
add('Interactive comparison exercise',['Open the demo and pause at original frame 50.','Select a visual inlier, then switch to LiDAR and inspect a correspondence.','Toggle accumulated mapping and compare the map outputs.'], 'Students need only a browser and the supplied page. Ask them to explain which residual each method minimizes, why a tracked feature may be unused, and why the visual map cannot be reported in meters. The checkpoint is a growing map with frame-specific additions and a visible estimated path.',[K,CV,L],layout='visual',media='comparison.png',demo='visual')
add('Student deliverable',['Capture one image track and one LiDAR correspondence.','Explain how each observation constrains pose and contributes to the map.','Compare GPS, terrain models, and missing loop closure in the controlled scenario.'], 'Expected answer: visual tracks constrain projection of established 3D landmarks, while LiDAR surface correspondences constrain alignment along normals. Successful registration lets sensor observations enter a common map frame. A complete answer states that the visual demo has arbitrary scale and both traces omit global SLAM correction.',[CV,L,V])
add('Discussion',['Can a well-tracked distant feature still have poor depth?','Why can a single plane leave some motion directions uncertain?','Can a closed trajectory still contain a distorted map? What can GPS fix?' ], 'Answers: yes, small parallax makes depth unstable despite reliable tracking. One plane provides normal-distance constraints while allowing sliding within the plane and rotation around its normal. Verified revisits, repeated map associations, BA or graph optimization, and possibly external anchors improve long-term consistency. Ask students to name the actual constraint rather than simply say more sensors.',[CV,V,L])
add('Lecture resources',['Online: real KITTI replay plus GPS, terrain, and drift experiments.','Offline: open Labs/Mapping/index.html from the lecture package.','References and implementation scope appear in the demo and slide notes.'], 'The offline package includes the slides, frames, precomputed traces, and the controlled experiment. New topics: GPS factors, slopes, bumps, failure recovery, absent loops and map rebuilding. No NAS connection is needed for students. Attribute the KITTI frames and derived data under CC BY-NC-SA 3.0. Algorithm references are teaching context; the demo is a compact implementation of selected local mapping steps.',[K,V,L,O],layout='resources')
for slide in C:
 if any(name.startswith('challenge-') for name in slide['media']):slide['demo']='challenge'
(H/'content.json').write_text(json.dumps(C,indent=2)+'\n')
print(len(C),'slides')
